### ISSUE TITLE
Init Bootstrap

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#1]
Pouzili by sme bootstrap (http://getbootstrap.com/), v ktorom si urobime custom temu.

- kym sa to inituje, moze sa bootstrap nalinkovat priamo: https://github.com/keboola/developer-portal-ui/blob/c0eed74/public/index.html#L17
- potom by sa spravili dve veci:
  1. uprava boostrapu a jeho farbiciek a fontov tak, aby sa dal vlastne pouzit kdekolvek (nemusi to mat use case, no je lepsie, ked z toho vznikne "developer portal theme", ako nejaky custom na mieru bordel)
  2. potom sa tato tema zobera a separatne sa dostyluju dalsie veci, co su specificke pre dev portal (ako homepage, a pod.)

Vysledkom by bola spominana tema (vlastne len zmenene variables.less/sass), ktora by sa pouzivala a dalej modifikovala.

Cele sa to vlastne moze diat vramci tohto repa (ak sa rozhodneme, potom mozeme tu temu vyhodit ako samostatny project)

Pocas toho (ak bude potrebne), mozeme z tej temy skusit vykopnut style guide.

**Comment by janmichek** [comment]
@ujovlado Caj, ted na to koukam a zda se ze jsi vybral nastroj pro vsechny budouci appky. Skoda ze neprobehla nejaka diskuze jestli bootstrap v3 / v4 nebo jestli vubec bootstrap. Uplne s tim nejsem v pohode. Mrkni na moj analyzu tady. https://keboola.slack.com/archives/C1QDG26DR/p1495111736617945

**Comment by ujovlado** [comment]
@janmichek ako som pisal, nehadzal by som flintu do zita, preto je tu aj ta issue ... to ze spravim teraz nejaky init pre dev portal v bootstrape neznamena, ze to tak ma byt skrz vsetky Keboola veci ;) (vid. slack)

Plati ale to, co pisal @kacurez , ze ak pouzivame `react-bootstrap`, asi to bude schodnejsie.

Je to este len zaciatok, cele to moze vypalit inac. Prve dni riesim len init projektu a veci okolo....

**Comment by ujovlado** [comment]
Solved in #19
