### ISSUE TITLE
App list contains only one app when user didn't visit app page

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#101]
Po vytvoreni aplikacie mam v liste len tu novu app, ostatne mi zmizli

**Comment by kacurez** [comment]
@ujovlado to sa mi nepodarilo nasimulovat, mozes popisat presne kroky?

**Comment by ujovlado** [comment]
Tiez mi to uz fici, hmm ... ok, zavrem to tu a ked tak otvorim (ale fakt sa mi to stalo).

**Comment by ujovlado** [comment]
```js
case CREATE_APP_SUCCESS:
      let vendorApps = state.appsByVendor[action.vendor] || [];
      vendorApps.push(action.newApp);
      const newApps = {...state.appsByVendor, [action.vendor]: vendorApps};
      return {...state, appsByVendor: newApps, errorMessage: null}
```

^ tu je jasne vidno, kedy to nastane. T.j. napr. vtedy, ked som este nebol na stranke z apkami  (nemam ich v store)

**Comment by ujovlado** [comment]
Je tam ale ja dalsi problem ... a to, ze ta app nema atributy, ake by mala mat (v liste nie je flag public/private, chyba verzia a pod.)

**Comment by kacurez** [comment]
- po vytvoreni apka ani na backendu nema verzi(mozno verzi 0 alebo 1) a je vzdy automaticky private
- co sa tyka zleho vylistovania apiek po vytvoreni tak problem je tu: https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/admin/actions/apps.js#L18
Fixnem to tak ze routa `create-app` bude tiez nacitavat zoznam apiek(loadVendorApps)

**Comment by ujovlado** [comment]
- to 1. to je len docasne riesenie ... akonahle budem chciet dat na list appiek nejaky dalsi field, ktory nenastavis pri vyutvoreni, tak to nebude ficat .... mali by sme tam spravit novy get na detail app (na developer portal som uz zadal issue, sere ma ze to nevracia v odpovediach updatnute entity)
- 2. ok, pridaj to tam

**Comment by ujovlado** [comment]
^ nova apka ma veriu 1
