### ISSUE TITLE
Set default app type to "Please select ..." not "extractor" when creating new app

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#102]
User by mal explicitne poveda aku app chce.

**Comment by ujovlado** [comment]
toto mozeme zbuchnut az sa to bude prerabat na redux-form ;)

**Comment by kacurez** [comment]
fixol som to teraz(vid #108), potom ked sa to bude prevadzat na redux-form tak to bude jedna "velka" issue, tak aby sa to nemiesalo.
