### ISSUE TITLE
Show "Make public" only if app is prepared for publication/submission

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#116]
Myslim, ze je zbytocne userovi zobrazovat button "Make public", ak tu app stejne nevie odoslat na schvalenie.

Momentalne sluzi ten modal zaroven ako informacny, no myslim, ze by sme to mohli zahrnut rovno do editacie - t.j. app bude mat tieto fieldy required (asi uz aj ma, az na ikonku).

**Comment by kacurez** [comment]
podla mna to zbytocne neni, minimalne user vie ze moze urobit `Make Public` a odkial sa to robi a co k tomu treba. Synchronizovat ten stav(ci moze dat public abo ne) aj na frontende mi pride zbytocne - teoreticky moze dojst k chybe tj apka je k publikovaniu ale ui to nejak nezachytilo pretoze sa zmenili podmienky na backendu(napr long description uz netreba), alebo zle syncnuty stav(treba refresh stranky)...

**Comment by ujovlado** [comment]
Ok, davam "won't fix". Pri kazdej app, co nie je public sa zobrazi "Request approval".
