### ISSUE TITLE
Uncaught in Promise while requesting app approval.

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#117]
![screenshot_2017-07-21_16-55-44](https://user-images.githubusercontent.com/419849/28469266-0659cd86-6e36-11e7-92f1-db9a922f3b20.png)

https://github.com/keboola/developer-portal-ui/pull/109#issuecomment-317024562

**Comment by kacurez** [comment]
to neni bug a je to tak schvalne :)
confirmDialog sa po resolvnuti promise approveApp automaticky zavrie. Preto ten promise je rejectnuty a nikde sa nezachyti, co nicomu nevadi pretoze reducer ten failure zachyti a zobrazi chybovu hlasku v tom dialogu:
![image](https://user-images.githubusercontent.com/1412120/28615091-3565b336-71f8-11e7-94aa-1df3c7557cdf.png)

rovnako sa spracuvavaju getData v routes.js pre jednotlive routy, akurat stym rozdielom ze sa to rethrowne ako HttpError a nikde sa to nezachyti/nezpracuje.

**Comment by ujovlado** [comment]
Ale to je predsa kravina ... ma sa to zachytit a v pripadne potreby prebublat vyssie (napr. do tej error hlasky).

Predstav si, ze uz mame setupnute sentry ... kazdy takyto error tam skonci (budeme ich potom ignorovat?)

Myslim, ze v routes sa ten HttpError sa praveze odchyti, inac by nemalo vyznam ho vyhadzovat.

**Comment by kacurez** [comment]
este som si uvedomil ze vsetky uncaught errory z promisov ktore ui produkuje zachyti ta notifikacna lista s errormi ked sa tam dorobi(ako ma kbc-ui). V tom pripade sa ta chyba zobrazi 2krat co by nemusela. Nechal by som to zatial tak a ked bude dorobena ta notifikacna lista tak to nejak vymyslim.

**Comment by kacurez** [comment]
> Myslim, ze v routes sa ten HttpError sa praveze odchyti, inac by nemalo vyznam ho vyhadzovat.
v routes na reject vidim len `throw new HttpError(error.status, error.statusText);` a nevidim ze by bol `found` nejak nakonfigurovany aby to zachytaval..

> Predstav si, ze uz mame setupnute sentry ... kazdy takyto error tam skonci
ak plati to co pisem vyssie podobnych errorov tam skonci viac napr aj z fetchVendors alebo fetchAppDetail

**Comment by kacurez** [comment]
aha uz vidim ze by sa to malo zachytit tu:
https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/App.js#L22

**Comment by ujovlado** [comment]
https://github.com/keboola/developer-portal-ui/blob/bd12626/src/scripts/modules/App.js#L7 ... vacsinou to spadne do toho `default` - tie error kody som len skusal ...

Toto vobec nie je o notifikacnej liste - ta nam hlavne odchyti netowrk errory (teda mozno aj dalsie).

Ak sa ti do toho nechce, kludne to fixnem.
