### ISSUE TITLE
dont validate login form on redirect to create-account/forgot-password

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#119]
narazil som na zaujimavy bug:
- som ako uzivatel odhlaseny a vojdem na stranku s loginom http://localhost:3000/app/auth/login
- dam focus na Email address pole ale nic nevyplnim
- kliknem na create-account alebo forgot-password link a dostanem chybu `Email can't be blank`(viz screenshot)
- po opatovnom kliknuti na jeden z linkov ma uz spravne presmeruje na ziadanu stranku

![image](https://user-images.githubusercontent.com/1412120/28522757-a4a75496-7079-11e7-8262-123784a9ec64.png)

**Comment by ujovlado** [comment]
ta validacia na jednotlivych fieldoch sa robi na `onChange/onBlur` ... ty si do toho fieldu vosiel a nic si nevyplnil, tak ti zahlasilo error ... takze myslim, ze to je zelane chovanie a s kliknutim na "Forgot password" a pod. to nesuvisi.

**Comment by ujovlado** [comment]
ako by sa to malo podla teba chovat? :)

**Comment by kacurez** [comment]
ked kliknem na Create Account(resp Forgot Password) tak sa nic neudeje, len vyskoci chyba - ja cakam ze ma to presmeruje na stranku Create Account(je to obycajny link) ale tak to vyzera akokeby sa snazil submitnut ten formular a preto ho zvaliduje. Az ked kliknem na Create Account link druhy krat tak ma spravne presmeruje.
za zelane chovanie povazujem napr. tak ako je to tu: https://connection.keboola.com (ked som odhlaseny)
ale ziadna tragedia to nieje, berem to ako low-prio :)

**Comment by kacurez** [comment]
dalsia vec co ma pri tej chybe ako usera napadne je ze ked tam vyplnim email, stlacim na Forgot Password tak to hned odosle ziadost o reset hesla

**Comment by ujovlado** [comment]
no ale to nie je bug ... proste sa to validuje ... mozes kliknut hocikde mimo toho formulara a ten error ti vyskoci, lebo sa spravila validacia.

navyse, ked to tu skusam, na "Forgot password" sa mi ani neda kliknut, lebo ten form poskoci:

![peek 2017-07-24 16-32](https://user-images.githubusercontent.com/419849/28528356-c18eebfa-708d-11e7-9369-0733d8fb1453.gif)

**Comment by kacurez** [comment]
aha takze na ten link nekliknem len to poskoci, to som si vsimol az teraz, vypada to akokeby som nanho klikol. Mne to pride divne/matuce a to si myslim ze ako user som celkom blbuvzdorny :)

**Comment by ujovlado** [comment]
Neviem, no ... to chovanie, co popisujes mi pride strasne specificke (az divne) - pridem na login page, vojdem to "username" fieldu, nic nezadam a nasledne stlacim forgot password. Netvrdim, ze sa to nemoze stat, len neviem, kde je ta chyba (to sa mozes stazovat, ze si klikol na "Apps" dole a udialo sa to iste) - proste inak ako kliknutim mimo (alebo prejdenie na iny field) sa ten focus nestrati.

To ako je to na connection sa mi nepaci, lebo to umoznuje odoslat prazdny formular. Je spravne dat userovi vediet, co vyplnil zle, este pred odoslanim na server.

**Comment by kacurez** [comment]
narazil som nato necielene/nahodou ako BFU a ma to aj trocha zmiatlo, preto som to bral ako validnu issue. Uvidime ci pride podobny feedback aj od userov :)
tu to zatvorim
