### ISSUE TITLE
Nacitanie dat / store

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#12]
Related to #3 

- ~rad by som to spravil co najjednoduchsie a pouzil `fetch()`: https://github.com/github/fetch~ vybavene, uz len ako ten store
- to otvara otazku ako pracovat so store

**Comment by kacurez** [comment]
co myslis tym store? flux/redux store alebo ako obecnejsi pojem?

**Comment by ujovlado** [comment]
@kacurez jo to co pises, ci tam skusime dat nieco hotove alebo to skusit po svojom. Zalozil som to prave nech to prebereme.

Si tusim spominal, ze by sa to cele mohlo drzat na hlavnej komponente?

**Comment by kacurez** [comment]
jj bavili sme sa otom ze by kazda routa(= top react komponenta stranky) vo svojom react state drzala data z api + data z loginu ktore pocitam ze nacita z localStorage. Zaroven sa tym obmedzuje pouzitie dat z inej routy(co moze byt problem). 
takze napr stranka/routa detail apky by z api nacitala iba detail apky atd..
Zaroven sa trocha bojim ze si tym vo vysledku naprogramujeme svoj redux/flux :)

**Comment by kacurez** [comment]
hmm ale rozmyslam ze to bolo dost komplikovane v momente ked na tej stranke zacnes volat patch resp post api cally tj nieco menit tak aby sa to zobrazilo aj na tej stranke. Si myslim ze vo vysledku bude menej prace pouzit redux/flux uz od zaciatku.

**Comment by ujovlado** [comment]
pozeral som este ten redux a skusam sa s tym trosku bavit ... dal by som ho tam

**Comment by kacurez** [comment]
jj ten redux mi pride ako standart na js react stack

**Comment by ujovlado** [comment]
Zatvaram, dal som tam redux ;)
