### ISSUE TITLE
Update vendor details

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#133]
ak obycajny user moze zmenit info vendora tak by to malo byt mozne na `user details` stranke:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/update-vendor

![image](https://user-images.githubusercontent.com/1412120/28629456-c7b77448-7227-11e7-93d1-a319507aebee.png)

Co sa tyka zmeny user details tak tam vlastne nic neni mozne zmenit. Reset hesla by som dal prec, zmenit heslo je mozne len cez forgot-password

**Comment by ujovlado** [comment]
toto by som rozbil na 3 casti:

1. vyhodenie stredneho panelu (mozem spravit hned)
2. uprava zobrazenie vendorov
3. moznost editacie vendora (az neskor)

**Comment by ujovlado** [comment]
1. vyhodene :white_check_mark:  ed695f2
2. #139
3. v tejto verzii to imho netreba, dam to do milestone "Next" #140

**Comment by ujovlado** [comment]
Toto teda zatvaram
