### ISSUE TITLE
Superadmin layout&functionality

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#135]
Po prihlaseni ak je user superadmin(tj dev keboola) tak mu je umoznene vidiet a nastavovat:
- vsetky apky (approve apky, super edit, delete)
- vsetkych userov (approve usera, priradovat k viac vendorom, delete, nastavit ako superadmina)
- vsetkych vendorov (approve vendora, edit vendor details)

+ bezne menit a vidiet to co moze "bezny" prihlaseny uzivatel

admin api:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/list-users

![image](https://user-images.githubusercontent.com/1412120/28630089-96c9e7d8-7229-11e7-9156-439d800bf673.png)

**Comment by ujovlado** [comment]
Toto zavrem s resolution "splitted" ... mame na to nove tasky, o ktorych sme sa vcera bavili.
