### ISSUE TITLE
Edit App Review

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#136]
Skusil som si preklikat edit apky a mam k tomu 2centy, no teda 4 :) 

1. **Back button** - som v zozname apiek, dam edit, chcem sa vratit spat na zoznam ale back button link ma navedie na detail apky, je tam `← Back to app detail`, spravne by v tomto pripade malo byt `← Back to apps list`
2. **General Save Error** - ked na svojej 13ke zaskrolujem uplne dolu k save buttonu, stlacim save tak sa nic nedeje, musim vyskrolovat hore a zistim ze napr short description je prazdny a musim ho vyplnit. Tu by som ocakaval nejaku message pri save buttone ze "formular sa neulozi pretoze je nevalidny a zkontroluj ho". V jednom z navrhov errors-notifications od Jacka to je nacrtnute (https://keboola.slack.com/files/jancermak/F67KJVAFP/form_error_1x.png)
3. **Ikonka** - ked uploadnem ikonku(change app icon -> drag&drop -> upload) tak po zavreti modalu mi ostane na boku stale zobrazena stara ikonka. Ked prekliknem ui (back to app detail) tak sa to uz updatne/zobrazi spravne.
4. **Popisky/napoveda** - ui malo napoveda, niektore polozky su jasne ale u niektorych vaham aj ja  takze si to musim bokom dohladat. Obecne ten problem vidim hlavne pri UI Options ale aj Network(Birdge/None), Default bucket , Encryption, Fees, Logger... Minimalne by bolo dobre to prepojit s helpom, pridat tooltipy(ak to neni moderny ux antipattern), alebo vymysliet inu formu -> prehnat cez Jacka.

**Comment by ujovlado** [comment]
1. doladime, myslim, ze by stacilo vyhodit "<- Back" a dat tam "Go", tym by bolo jasne, ze je to odkaz a nie krok s5.
2. pri dlhych formularoch by sa hodilo dat dole aj upozornenie na "client side" error - dobry point
3. uz je na to issue: #123 
4. ano, este by to nieco chcelo ale nechal by som to az na koniec, ked to budeme davat Jackovi na review

**Comment by ujovlado** [comment]
1. a 2. opravne ... 3. uz ma issue a 4. neskor, tak ako som pisal.
