### ISSUE TITLE
[superadmin] Edit vendor

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#143]
Na liste vendorov je pri kazdom vendorovi "ceruzka", ktora otvori modal pre jeho editaciu.
![screenshot_2017-07-28_09-49-19](https://user-images.githubusercontent.com/419849/28708086-23dee6b2-737b-11e7-9106-1c2f593011d9.png)

Mal by sa na to dat pouzit:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/update-vendor

Navrh:
![screenshot_2017-07-28_09-50-47](https://user-images.githubusercontent.com/419849/28707855-3f1dc6d8-737a-11e7-8506-f03371e28603.png)

**Comment by kacurez** [comment]
som zistil ze edit vendor v superadmine nepojde pretoze nato neni podpora z backendu. Ten api call nepovoluje editovat cudzieho vendora v ktorom ako user niesom. zalozim issue v dev portali

**Comment by ujovlado** [comment]
ok, tu issue zaloz (ak si este nie) ... rozmyslam ale, ze by sme aspon mohli povolit editaciu pre vendorov, ktorych som clenom (mam ich v profile.vendors), to by slo nie? a potom ked sa upravi API, vlastne len vymenime API call za adminsky.

**Comment by ujovlado** [comment]
^ t.j. tu ceruzku na editaciu by si mal zatial len pri vendorch, ktorych si clenom

**Comment by kacurez** [comment]
hej rozumiem, rozmyslam nadtym rovnako, asi to nebude problem urobit..

**Comment by kacurez** [comment]
issue na dev portal https://github.com/keboola/developer-portal/issues/129
