### ISSUE TITLE
[superadmin] Change user's vendor membership

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#146]
Toto bude asi kombinacii API callov:
- http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/add-user-to-a-vendor
- http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/remove-user-from-a-vendor

Navrh:
![screenshot_2017-07-28_10-08-23](https://user-images.githubusercontent.com/419849/28708482-b682ebd4-737c-11e7-9c88-8fc182c4f827.png)

Pouzil by som na to react-select (uz je v projekte), ktory sa chova podobne ako v navrhu.

Za uvazenie by tiez stalo, ci to nespravime len "one at a time", aby sa vendor k userov bud pridaval alebo odoberal. Ale asi by to nemuselo byt komplikovane ani prvy sposobom, len sa bude musiet spravit diff a na zaklade toho API cally.

**Comment by kacurez** [comment]
ja by som urcite spravil one time, tj by namiesto tuzky v tabulke bolo bud add alebo remove ikonka. Create vendor by som do toho tiez nedaval, pretoze ten vyzaduje viac policok a tiez to generuje 2 api cally. Navyse je to admin rozhranie(pre nas) a viac ako super ux potrebujeme aby to bolo atomicky funkcne, aspon na zaciatok.

**Comment by ujovlado** [comment]
Este mi napadlo, ze by sa to dalo naviazat na to, ako vyberas v tom Selecte ... ze by to mohlo rovno posielat tie API cally ... a nemuseli by sme riesit diff ...  a save changes button by sme potom museli dat prec.

**Comment by kacurez** [comment]
to uz mi pride moc agresivne, ze lepsie to mat s confirmom(save changes). Urobim to co najjednoduchsie podla toho ako to podporuje api.

**Comment by ujovlado** [comment]
Jo, vpoh, tak ako si pisal to prve "one at a time"
