### ISSUE TITLE
[superadmin] Approve developer?

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#147]
Tu som si nie uplne isty, ci to pojde, resp. ktory API call pouzit. Ale asi to iste, co na pridanie do vendora:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/add-user-to-a-vendor

Navrh:
![screenshot_2017-07-28_10-17-09](https://user-images.githubusercontent.com/419849/28708823-eeb351be-737d-11e7-96a4-4cf32e2d62e9.png)

Mozeme s tym pockat, prejst to, oznacim to ako "discussion".

**Comment by kacurez** [comment]
toto je invalid ^^
pretoze user ziada o pridanie do konkretneho vendora:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/invite-user-to-a-vendor
a ta ziadost pride vendorovi emailom ktory kliknutim na link ziadost potvrdi.
Nikde sa tie ziadosti nedaju vylistovat, v superadmin sekcii urcite nevidno ziadosti jednotlivych userov o pridanie do vendora. Jedine co my ako admini mozme urobit je natvrdo pridat usera do vendora alebo ho odtial odstranit.

**Comment by kacurez** [comment]
vytvoril som si novy account a sledoval co sa bude diat v superadmin sekcii. Prisiel mi confirmacny email na ktory som klikol, potom som sa prvykrat prihlasil, vybral vendora a dal submit. Teraz v superadmin sekcii vidim u toho uzivatela toto
![image](https://user-images.githubusercontent.com/1412120/28820008-4dbfad4e-76b0-11e7-962a-02f77e0f0169.png)
- nevidim do ktoreho vendora sa chce pridat(ak vobec chce)
- vidim ze potvrdil konfirmacny email, tj neni potrebny ziadny approve zo strany superadmina

Z toho vyplyva ze ten status stlpec je +- zbytocny, mohli by sa unconfirmed users v tej tabulke iba zasednut a vlastne to len znamena ze si nepotvrdili email.

**Comment by ujovlado** [comment]
@kacurez tak toto by som zavrel a vytvorim task na pridanie developera ("Add developer"), ktory nam myslim chyba

**Comment by kacurez** [comment]
@ujovlado co znamena "Add developer" - neni to add existing/confirmed user to vendor? pretoze teraz robim na tom stlpci vendors a vlastne tam stym pracujem tiez 
https://github.com/keboola/developer-portal-ui/issues/146

**Comment by ujovlado** [comment]
je to toto #169 , api call: http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/add-user-to-a-vendor

**Comment by ujovlado** [comment]
Toto teda zatvaram, approvovat sa z UI neda, podla toho co pises ;)

**Comment by ujovlado** [comment]
To UI bude podobne ako v tom co robis, ano
