### ISSUE TITLE
[superadmin] List of apps

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#148]
List vsetkych apps:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/list-apps

Navrh:
![screenshot_2017-07-28_10-26-14](https://user-images.githubusercontent.com/419849/28709133-33677276-737f-11e7-8a2a-dd02d8d52d79.png)

Sucastou by malo byt filtrovanie (ako v navrhu):
- podla statusu
- podla mena autora, etc.

V tomto tasku sa nerobi:
- schvalovanie
- edit
- remove

Co zatial nevieme spravit:
- usage
- je tam nejaky odkaz "repository link" uz si nepamatam co to bolo (mozno odkaz na docku?)

**Comment by kacurez** [comment]
list of apps by sa imo hodilo aj na agegovanie poctu apiek na vendora resp usera. Tj by bol redux store ktory vrati pocet apiek a vypocita si to prave z toho api callu GET /admin/apps. Zaroven by asi musel byt niekde vyssie na route pretoze tie pocty sa renderuju v developers a vo vendors sekcii

**Comment by ujovlado** [comment]
@kacurez no to by bolo pekne, ale tych apps je tam okolo ~350 a uz je to hodne pomale, tak rozmyslam nad tym, ze tam dam strankovanie.

Malo by to skor vracat API, je myslim kravina si to ratat na UI a kvoli tomu fetchovat vsetky apky ;)
