### ISSUE TITLE
use immutablejs instead of js plain objects

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#15]
ako som zvyknuty nato z kbc-ui tak tu by som to tiez rad videl, ajked vsetko je skryte za reducere no imho zapis ako `Object.assign({}, state, {...})` je dost neprehladny.
V tomto clanku ako alternativu odporucaju tzv spread operator tj `{...state, isLoading: action.isLoading}`:
http://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html
ale tiez k tomu treba doinstalovat podporu pre babel cez plugin.
Pisem to teraz lebo je este "cas" a moznost to zmenit ak sa natom dohodneme.
ci?

**Comment by ondrejhlavacek** [comment]
Nedávno jsem na tohle téma četl https://medium.com/@AlexFaunt/immutablejs-worth-the-price-66391b8742d4

**Comment by Halama** [comment]
mě se  s tím pracuje dobře, bez něj si datový transformace neumím představit

**Comment by ujovlado** [comment]
@kacurez ten spread operator treba doinstalovat, jo ... zatial som to neriesil, neprislo mi to ako nejaky problem. Mozno na tro mozeme prejst ked to bude podporovane nativne?

**Comment by ujovlado** [comment]
@kacurez ten Object.assign je tam takisto ako polyfill

**Comment by ujovlado** [comment]
Myslim si, ze zatial tam immutablejs netreba ... vsetky reducery musiia byt immutable a napiseme na ne testy.

**Comment by kacurez** [comment]
- ak by sa pouzil immutablejs tak testy na immutabilitu reducerov pisat nemusime :)
- co sa tyka transformacii plain js objetov tak sa mi stalo ze nieco nepodporoval IE, z toho mam v hlave zasek ze je to nejednotne, preto to radsej pisem cez nejaku libku(underscore, immutablejs) ktora to ma zjednotene pre vsetky browsre.
- moze to byt dobry "experiment" na porovnanie (vyvoj bez immutablejs)
- ten spread operator je sikovna vec, hodi sa naucit stym robit, ak nevadi tak by som to rovno nainstaloval a pouzil

**Comment by ujovlado** [comment]
- ak by to niekomu extremne nevadilo, skusil by som to zatial bez immutable (je to mala appka)
- IE :)
- jj, to chcem!
- object spread tam uz je, mozme to pouzivat

**Comment by kacurez** [comment]
ok tak to skusme bez immutablejs, dufam ze nebudem plakat ked zistim ze uz neni getIn/setIn :))

**Comment by ujovlado** [comment]
getIn -> prepises cez bodky
setIn -> to imho nebudes potrebovat vdaka reducerom a ich skladaniu :)
