### ISSUE TITLE
Filter public aplikacii

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#16]
- momentalne je tam urobeny smiesny list aplikacii (nacita to 10 appiek) a filter je cez path (`/apps/extractors`), co sa mi nepaci, len som to testoval.

Malo by to byt asi takto:
- data filtra by som nacitaval z URL - vyhoda je, ze budeme vediet niekomu poslat napr. link na nase extractory (napr. `/apps?type=extractor`)
- vsetky parametre by som ziskaval ako query, aby bolo mozne ich kombinovat (napr `/apps?type=extractor` alebo `/apps?type=extractor&no-charge=1` alebo `/apps?type=writer` a pod.)
- fajn by bolo spravit aj ten search - asi vobec nemusi byt "on the fly"

Ked tak nad tym dumam, cele to moze byt "get form", ktory sa normalne submitne a nasledne sa sparsuju query params a spropaguju dalej.

Design toho netreba zatial riesit, spravim to v ramci issue #13

**Comment by ujovlado** [comment]
![screenshot_2017-05-22_11-08-13](https://cloud.githubusercontent.com/assets/419849/26301329/2d2156ca-3ee1-11e7-9a7c-1e41861f3bb7.png)

**Comment by ujovlado** [comment]
A tato routa je tym asi potom zbytocna: https://github.com/keboola/developer-portal-ui/blob/80e566a/src/components/App.js#L37

**Comment by kacurez** [comment]
si odlozim: parsovanie query nejak react router neumoznuje, zatial som nasiel toto riesenie:
https://github.com/keboola/kbc-ui-oauth-external/blob/master/src/components/App.jsx#L102
tj `let token = QueryString.parse(window.location.search).token || '';` 
cez libku https://github.com/sindresorhus/query-string
Do tych query params bude treba zapocitat aj paginacne parametre api(`offset` a `limit`)
http://docs.kebooladeveloperportal.apiary.io/#reference/0/public-api/list-published-apps

**Comment by ujovlado** [comment]
Tie offset/limit by som zatial vobec neriesil ... myslim, ze ked mame tych appiek do 200, kludne by som to nechal na UI a nesral sa s tym -> t.j. nejaky Pagination component mozeme asi spravit neskor

**Comment by ujovlado** [comment]
Resp. neviem kolko je ta hranica, kludne asi aj viac ( 500? 1000?)

**Comment by kacurez** [comment]
jj tak dajme tomu 500, ale v momente ked sa tam zavedie paginacia tak bude problem filtrovat komponenty na frontende. Napr zadas filtrovat extraktory ale prvych 500 komponent kt. api vrati budu writere takze 1. stranka bude prazdna..dobry riesenim by potom bolo zaviest rovnake filtrovanie aj na backende.

**Comment by ujovlado** [comment]
@kacurez jo, rozmyslal som nad tym rovnako, preto zatial to stankovanie nechcem riesit

**Comment by ujovlado** [comment]
aj tato vyzera fajn: https://github.com/ljharb/qs
