### ISSUE TITLE
[superadmin] Add developer

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#169]
To je to tlacitko vpravo hore a potom pod tabulkou

![screenshot_2017-08-01_15-07-56](https://user-images.githubusercontent.com/419849/28826799-a5c33270-76cb-11e7-854e-bb8a165d6282.png)

Adminsky API call: http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/add-user-to-a-vendor

Modal:
![screenshot_2017-08-01_15-17-55](https://user-images.githubusercontent.com/419849/28827088-b992e0a6-76cc-11e7-8c25-78762205694e.png)

**Comment by kacurez** [comment]
prave vymyslam ako poriesit to edit vendors(https://github.com/keboola/developer-portal-ui/issues/146) a vychadza mi ze to umozni bud pridat vendora alebo odoberat. 
A tu som si uvedomil ze Add Developer je vlastne z polovice to iste..

**Comment by ujovlado** [comment]
Ano, je to podobne, takze ked to uz takmer mas, iba dobre :)
