### ISSUE TITLE
Optimize speed of admin apps filtering

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#171]
Je to hodne pomale, tych apiek je tam momentalne 306 a filter cez redux store trva vpohode aj 1s.

Treba to poriesit inak, alebo tam pridat strankovanie (co api podporuje)

![screenshot_2017-08-02_11-33-01](https://user-images.githubusercontent.com/419849/28867424-618ba9ba-7776-11e7-8c7b-e49a30e52579.png)

**Comment by kacurez** [comment]
ak by sa to filtrovalo iba podla `id` apky? - myslim ten search bar filter, a potom by tam mohol byt zvlast select na filter podla typu(extractor, writer, application). 
Pretoze cez id apky si vlastne schopny ofiltrovat vsetko - vendora, typ a meno. napr keboola.ex-google-drive. Ak to ma sluzit len pre nas tak mne osobne filtrovat iba cez id bohate staci.

**Comment by ujovlado** [comment]
jo, este sa s tym potom pohram ... typ by sa mohol dat ako samostatny filter, to ano

**Comment by ujovlado** [comment]
Toto je len pre adminov, zatial nas to nepali. Co sa tyka tych "violation: input handler took ...", tak to fixneme pridanim debounce.
