### ISSUE TITLE
[superadmin] approve vendor via hotlink

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#173]
ak uzivatel vytvori vendora tak je potreba ho approvnut 
http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/approve-vendor
- do slacku spadne notifikacia napr:
```
User Company Name test <tomas.kacur@keboola.com> requires creation of vendor Company Name test with temporary id _xxxyyy
```
- superadmin zoberie temporary id `_xxxyyy` zavola approve api call v tele s novym id ako parameter `newId` v tele api callu.

Nato by sme mohli mat url ktora by sa tiez posielala do slacku nieco ako:
https://dev-portal.keboola.com/app/admin/vendors/_xxxyyy/approve?name=compnay%20name
superadmin nato zo slacku klikne a ak je prihlaseny tak nanho vyskoci confirm modal s novym id vendora(vygeneruje sa z mena vendora) ktoreho popripade upravi a odklikne

**Comment by ujovlado** [comment]
Toto je celkom fajn napad, akurat to podla mna musi funguvat aj bez UI. T.j. keby nefungovalo, stale by si mal byt schopny schvalit vendora - co chapem, ze stale mozes (API call na approve). Issue je imho skor v tom, ze sa o tom nedozvies.

Asi by mal pribudnut adminsky API call, ktory ti vypise aj neschvalenych vendorov.

**Comment by kacurez** [comment]
tjn zatial jedine miesto kde sa zhromazduju ziadosti novych vendorov je slack(v support_maintanance)
Novy api call na vylistovanie neschvalenych vendorov by sa hodil, a imo sa to da vytvorit uz teraz zo sucasnych dat.

**Comment by ujovlado** [comment]
Toto zavrem, lebo:
- vendorov az tak casto nevytvarame
- ak tam aj nejaky link dame, imho bude stacit odkaz na `/admin/vendors`, kde to budes moct schvalit (a neschvaleni budu hore)
- a myslim, ze Jakub uz robi nejake zmeny aby sa dalo approvovat z UI a nie len zo Slacku.
