### ISSUE TITLE
[superadmin] developers list fixes

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#177]
momentalne to vypada takto:
![image](https://user-images.githubusercontent.com/1412120/28883181-d5334d5a-77ad-11e7-8020-c0388547f507.png)

#### Zoznam potrebnych/navrhovanych uprav:

- [x] stlpec createdOn presunut do stlpca Developer(pod email)
- [ ] stlpec vendors je ako cely klikatelny(na bunku) a otvori set vendors modal, (? moze sa blbo kopirovat text vendora ?)
- [ ] posunut ikonku ceruzky v stlpci vendors
- [x] stlpec status/is enabled vyhodit, unconfirmed usera oznacit badgom v stlpci Developer alebo zasednut
- [x] unconfirmed uzivatelov presunut na koniec zoznamu
- [x] nezobrazovat/filtrovat usera ktory ma isEnabled == false 
- [x] umoznit filtrovat userov podla nepotvrdenych vendorov - to je user ktoreho vendor neni v zozname public GET vendors napr:
![image](https://user-images.githubusercontent.com/1412120/28883461-daa5b376-77ae-11e7-9959-d26eb647ddc1.png)

**Comment by ujovlado** [comment]
Este by som pridal jednu dolezitu vec. Zobrazovat datum v lepsom formate, nie v tom 03/15/2017 (napr. 2017/03/15).

**Comment by ujovlado** [comment]
Ak su nieco z toho veci na ui/css, kludne to spravim.
