### ISSUE TITLE
[Superadmin] approve vendor

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#186]
http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/approve-vendor
v navrhu od Jacka to neni ale je to potreba, inac by sa novy vendori dali schvalovat len cez postmana :)
Pridam to do sekce vendors.

potom sa to moze urobit cez hotlink aby sa to dalo len prekliknut z notifikacie v slacku(vid #173 )

**Comment by ujovlado** [comment]
Je to v navrhu:
![screenshot_2017-08-04_15-06-18](https://user-images.githubusercontent.com/419849/28969839-7dd4912a-7926-11e7-9040-0abc27a0b9bd.png)

Akurat, ze neviem ten status (na co myslim uz je issue v devportali).

**Comment by ujovlado** [comment]
Tam toho asi bude viac, lebo momentalne sa to riesi cez ten public api call, ktory vracia len public vendorov, takze neviem ci to pojde bez upravy api.

**Comment by kacurez** [comment]
teraz to funguje tak ze ti do slacku spadne notifikacia request vendor approve s tmp id vendora. Ty to tmp id musis zkopirovat a zavolat api call approve(vid vyssie). Ina cesta neni, takze by som urobil Approve Vendor button ktory otvori modal kde zadas to tmp id a das confirm.
Este ma napadlo to dorobit do sekcie Developers do edit vendor modal a k akciam `Add/Remove` vendor pridat `Approve vendor` kde by si mal na vyber z tvojich vendorov ktory nesu approvnuti(co sa da zistit) ako napr:
![image](https://user-images.githubusercontent.com/1412120/28970104-92e2095c-7927-11e7-8a1c-68305fedc582.png)

Problemy/nedostatky:
- nemam plne info o vendorovi ktoreho idem schvalovat, v slack notifikacii je meno vendora a kto chce schvalit, pri najhorsom sa ten vendor po schvaleni da upravit(ked sa dorobi api call)
- niesom isty ci sa approvnutim zmeni tmp id na to id ktore user zadal pri jeho vytvarani, a ci ho teda neni treba zadat znovu, pretoze to je parametrom approve api callu

**Comment by ujovlado** [comment]
toto sa mi paci:

> takze by som urobil Approve Vendor button ktory otvori modal kde zadas to tmp id a das confirm.

^ priadal by som tam ale aj `newId`, co je urcite potrebne, aby sa tomu zmenilo ID a neostalo hento temporary. A ak by to bolo treba zeditovat, tak to je uz potom vec editacie vendora.

Do sekcie developers by som to nepchal.

**Comment by ujovlado** [comment]
Taketo nieco: 
![screenshot_2017-08-04_15-27-01](https://user-images.githubusercontent.com/419849/28970606-776150fa-7929-11e7-948b-2605859db93b.png)

A potom v modale len 2 fieldy `temporaryId` a `newId`

**Comment by kacurez** [comment]
hej tak to tiez myslim

**Comment by ujovlado** [comment]
Ok, super :+1: 

![screenshot_2017-08-04_15-32-28](https://user-images.githubusercontent.com/419849/28970829-334c0ea4-792a-11e7-911a-038bd56bd611.png)
