### ISSUE TITLE
Add library for notifications

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#192]
Nez to pojde public, este budeme musiet pridat tu notifikacnu library

**Comment by kacurez** [comment]
urobil som malu analyzu:
#### Co potrebujeme
Notifikovat uzivatela ze jemu alebo nam neide internet :)
#### Co mozno potrebujeme
- Notifikovat 400ky/500ky get api callov, vlastne getData prop na route komponente.
- Zjednotit info notifikacie(user bol pridany/pozvany, apka vytvorena)
#### Co nepotrebujeme
Notifikovat 400ky/500ky post/patch api callov pretoze tie sa zobrazuju na formularoch(asi vsade kde je throw SubmissionError)

#### Existujuce Library
vsetky robia to iste - niekde do pod root element prdnes ich setup react komponentu/kontajner a potom volas api na zobrazenie notifikacie + je tam stylovanie notifikacii takze import css suborov. Vsetky kniznice umoznuju timeout renderu notifikacie.

1. https://github.com/igorprado/react-notification-system - ma najviac stars(1417). Nepaci sa mi ze si stack notifikacii uklada do interneho state, a hlavne setup komponenta sa musi napojit v componentDidMount cez refs
2. https://github.com/pburtchaell/react-notification - menej stars(500), ale nenuti k takemu divnemu setupu ako 1. takze by sa dala lepsie napojit na nas redux stack. Stale pouziva interny react state.
3. https://github.com/JakeGinnivan/react-redux-notifications - malo stars(110) posledny update pred rokom, **redux** riesenie,  V prop notifikacnej komponenty definujes na aky action type sa ma vyrendrovat takze natvrdo viaze notifikacie k action type ako 1:1 stym ze posledna dispatchnuta akcia vyhrava.
4. https://github.com/nicmesan/react-redux-notification - najmenej stars(27), posledny update pred pol rokom, jednoduche **redux** riesenie, mozne vyfirovat s akoukolvek dispatchnutou akciou(cez key notification), stylovanie je mozne iba cez preddefinovane css classy(ziadny custom render som nenasiel)
5. ..vlastne riesenie vykradnute z tychto ^^

#### Takze?
Mne osobne sa paci 3.(https://github.com/JakeGinnivan/react-redux-notifications) 
- je postavena na reduxe, 
- umoznuje custom render bez komplikovanych css(https://github.com/JakeGinnivan/react-redux-notifications/blob/master/style.css)
- plne dostacuje nasim potrebam
Jedinu nevyhodu vidim ze vypada ze je malo udrziavana resp uz vobec.

**Comment by ujovlado** [comment]
^ super research, urcite chceme nieco redux-like ... tiez to este kuknem a napisem sem

**Comment by kacurez** [comment]
este som nasiel https://github.com/gor181/react-notification-system-redux co je redux wrapper nad 1. library(https://github.com/igorprado/react-notification-system)
Vyzera to v pohode akurat ze to neni uplne redux nativne riesenie.

**Comment by ujovlado** [comment]
Toto rozlusknem urcite dnes ... poobede na to zasadnem

**Comment by ujovlado** [comment]
Ad 1. - riesia to tam ale cez `context`, co sa neodporuca: https://facebook.github.io/react/docs/context.html  ... takze asi nic

Ad 2. - suhlas

Ad 3. - jo, vyzera celkom fajn, ale je tam middleware.

Ad 4. - vyzera to smiesne, jo

Este som nasiel:

5. https://github.com/indexiatech/re-notif ... tam sa mi celom paci, ze tam netreba pridavat middleware. ale je nejaka smiesna

6. https://github.com/LouisBarranqueiro/reapop tiez je tam ale middleware

**Comment by ujovlado** [comment]
Skusim 3. a 6. a jednu z nich tam pridam. 6. vyzera aktivnejsia.
