### ISSUE TITLE
Generate credentials for service account

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#206]
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendor/generate-credentials-for-service-account

Be able to generate credentials for component integration.

**Comment by kacurez** [comment]
momentalne ui tie servisne ucty filtruje a nezobrazuje, asi by ich potom malo aj zaobrazovat cez nejaky prepinac

**Comment by Halama** [comment]
ani jsem nevedel ze uz je umime listovat. ted mi ale chybelo hlavne zalozeni:)

**Comment by Halama** [comment]
jinak by mohli byt asi vylistovane na samostatne strance, necpal byhc je mezi developery

**Comment by ujovlado** [comment]
Ok, zatial asi spravime nieco taketo:

![screenshot_2017-08-10_15-36-38](https://user-images.githubusercontent.com/419849/29173001-180698dc-7de2-11e7-99b7-70c92d86e66c.png)

**Comment by Halama** [comment]
jo to je super
