### ISSUE TITLE
Allow all vendors editing for admin

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#207]
API by to uz malo podporovat, takze tu "ceruzku" mozeme dat ku vsetkym

**Comment by Halama** [comment]
ceruzku?

**Comment by ujovlado** [comment]
![screenshot_2017-08-10_11-17-53](https://user-images.githubusercontent.com/419849/29163732-a20719dc-7dbd-11e7-9f96-13063d348da0.png)

**Comment by kacurez** [comment]
https://sk.wikipedia.org/wiki/Ceruzka 
:)
