### ISSUE TITLE
Add newly created service account to accounts list

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#213]
Related to #210

**Comment by kacurez** [comment]
ale tam je force reload na get vendor users co to vlastne riesi a vola sa po create service accounts

**Comment by ujovlado** [comment]
aha, ok, uz vidim, no z nejakeho dovodu mi to nezafungovalo ...

**Comment by kacurez** [comment]
ok pozriem sa este nato, vlastne tiez sa mi to stalo ale tak mi to vratilo api(prazdny list users), som myslel ze to suvisi s problemom so strankovanim

**Comment by ujovlado** [comment]
asi by som pockal, ak sa upravi ten api call (https://github.com/keboola/developer-portal/issues/139), tak ziadny reload nebude treba a dame to tam rovno z response ;)

**Comment by ujovlado** [comment]
nemusis to hladat, vyzera to na bug v API .. necham to tu "on hold", mozeme sa k tomu vratit potom.
