### ISSUE TITLE
App listing - show type "other"?

### ISSUE THREAD

**Issue by pivnicek** [keboola/developer-portal-ui#217]
Apps that are of type "other" should maybe not be shown in the listing, they most likely aren't interesting.

see: 
![image](https://user-images.githubusercontent.com/569139/29260303-487b3f92-80c9-11e7-8618-3cee7b8d38ad.png)

**Comment by kacurez** [comment]
good point! I will filter it out from public list of apps

**Comment by kacurez** [comment]
fixed in 1bdf302e9bc7bb967bcee743603fe2f78f00d33c

**Comment by ujovlado** [comment]
Isn't good that people can discover that those types of apps can be run in our infrastructure?

I mean, why to hide them? If it's available in Keboola Connection, it should be also here.

For me, the solution for this is to set flag `isPublic` to false, not filter out "other" types ;)

**Comment by pivnicek** [comment]
I was thinking about that but nowhere in the UI is there a hint that there is such a thing as type 'other' so I thought it may be confusing.
Agree wrt `isPublic` though.

**Comment by ujovlado** [comment]
But if we end up with adding type "other" (e.g. to select box) and there will be no app, it's pointless ... so I don't know

**Comment by kacurez** [comment]
these are `other` components, 

```
{type: "other", name: "Data Takeout", uri: "docker/kbc-project-takeout", shortDescription: "Export project to S3"}
{type: "other", name: "Keboola Connection Project Takeout", uri: "docker/kbc-project-backup", shortDescription: "Export Project to S3"}
{type: "other", name: "Lucky Guess", uri: "rt-lucky-guess", shortDescription: "Lucky Guess"}
{type: "other", name: "Orchestrator", uri: "orchestrator", shortDescription: "Jobs scheduler"}
{type: "other", name: "Orchestrator", uri: "orchestrator", shortDescription: ""}
{type: "other", name: "pigeon", uri: "pigeon", shortDescription: "Pigeon is simple service, which provides importing files into KBC via email"}
{type: "other", name: "Provisioning", uri: "provisioning", shortDescription: "Transformation engine provisioning"}
{type: "other", name: "Queue", uri: "queue", shortDescription: "Queue"}
{type: "other", name: "R Worker for Lucky Guess", uri: "docker/keboola.r-luckyguess", shortDescription: "Lucky Guess R component"}
{type: "other", name: "R Worker for Lucky Guess (deprecated)", uri: "docker/docker-lgr", shortDescription: "Lucky Guess R component"}
{type: "other", name: "Shiny app deployment service", uri: "docker/shiny-app-deploy", shortDescription: "Internal service for deployment of shiny applications"}
{type: "other", name: "Shiny for Luckyguess", uri: "shinyapps/lg-shiny", shortDescription: "Shiny for Luckyguess"}
{type: "other", name: "SSH Keygen", uri: "https://ssh-keygen.keboola.com", shortDescription: "SSH keys generator"}
{type: "other", name: "Storage Table Importer", uri: "table-importer", shortDescription: "Imports data from files storage to tables"}
{type: "other", name: "XLS2CSV", uri: "docker/docker-xls2csv", shortDescription: "XLS to CSV convertor by Breezy"}
```
some of them user will never run or don't know how to run - so it provides incomplete info. The rest(valid apps) should be tagged as one of the types we use in the reset of dev portal(extractor, writer, application) no?

**Comment by pivnicek** [comment]
Since it's my issue, I'll go through and update them accordingly.

**Comment by kacurez** [comment]
to me its good, maybe we can ask for more opinions in slack? :)
still other components will be visible in admin and superadmin section(for us)

**Comment by ujovlado** [comment]
@pivnicek I see you self-assigned this. Is there anything what should be done from UI side? Otherwise, I would like to close it :)

**Comment by pivnicek** [comment]
@ujovlado ah shit, sorry totally forgot about it.  Will update this tomorrow.

**Comment by pivnicek** [comment]
huh, so you can't edit apps that are type `other` since there is no type `other` in the application type select.

**Comment by pivnicek** [comment]
sure, but what if you don't want to change type?  In the UI it forces you to change it

**Comment by kacurez** [comment]
ah I see, actually backend does not support `other` either: https://github.com/keboola/developer-portal/blob/master/lib/Validation.js#L165

**Comment by pivnicek** [comment]
oh, I didn't know that.  lol, tak `deprecated`?

**Comment by kacurez** [comment]
actually components with type `other` can be changed only via api/postman. UI does not support it because of the type inconsistency. So I would leave it till someone(of us only) wants to edit these `other` components.

**Comment by pivnicek** [comment]
so in that case they should be excluded from the UI app listing no?

**Comment by kacurez** [comment]
there are 2 listings where other components can be found:
1. public apps : https://portal.keboola.com/apps
2. superadmin section apps: https://portal.keboola.com/admin

I would leave it listed only in superadmin section apps(2.). 
For the public apps listing(1) I would set all unused other components to private(e.g. orchestrator) and all used other components to other type(e.g. data takeout change type to application). This way we get rid of other components from public apps listing.

**Comment by pivnicek** [comment]
ok, I changed `SSH Keygen` and  `XLS2CSV` to application and made the rest private

**Comment by ujovlado** [comment]
ok, great, so I'm going to revert 1bdf302
