### ISSUE TITLE
Cannot open login page

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#219]
Po kliknutí na `Account`
![image](https://user-images.githubusercontent.com/903531/29270122-816faa50-80f5-11e7-8833-8a0ae6251060.png)

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/29270205-e87128dc-80f5-11e7-9da2-e9f3a8173304.png)

**Comment by Halama** [comment]
A když jdu rovnou na login page, tak to zavolá jenom 200 OPTIONS a hodí mě na MFA screen:
![image](https://user-images.githubusercontent.com/903531/29270394-d33c1fca-80f6-11e7-8ad5-6a0811e2a461.png)

**Comment by ujovlado** [comment]
Nie su tam hlavicky:
![screenshot_2017-08-14_14-04-13](https://user-images.githubusercontent.com/419849/29270985-8f555ac6-80f9-11e7-820e-8fcb0faa70d5.png)

**Comment by ujovlado** [comment]
https://github.com/keboola/developer-portal/issues/140

**Comment by ujovlado** [comment]
Podla issue v predch. commente to je fixnute (aspon docasne). Tu to zavrem, kedze sa nejedna o bug v UI ale "3rd party".
