### ISSUE TITLE
copy to clipboard support for service account credentials

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#221]
Po vytvoreni credentials servisneho uctu si uzivatel credentials skopiruje, moze sa stat ze sa mu pritom podari zatvorit modal takze nic nezkopiruje a je nuteny vytvorit novy servisny ucet a stary zmazat.
Preto sa tam hodi copy to clipboard button:
![image](https://user-images.githubusercontent.com/1412120/29322795-20b689a0-81df-11e7-86a5-cf038c14c158.png)

bude potreba nainstalovat nejaku react clipboard kniznicu:
- na kbc-ui pouzivame https://github.com/nihey/react-clipboard.js
- este som narazil na jednu: https://github.com/nkbt/react-copy-to-clipboard - ma viac stars a devel vyzera byt aktivnejsi

**Comment by ujovlado** [comment]
Myslim, ze "copy to clipboard" nejako nepomoze tomu aby neklikol mimo ...

Skor som rozmyslal nedovolit zavriet modal, kym nebudeme mat zaznamenane ze klikol na obidva `pre` elementy zobrazujuce username a password - ale zda sa mi to trosku obmedzujuce a neviem, ci nemoze nastat nejaky edge case :)

**Comment by kacurez** [comment]
jasne ze sa vzdy moze kliknut mimo ale ak usera navedies aby klikol na konkretne miesto(copy to clipboard button) tak tym minimalizujes riziko ze klikne mimo.
alebo by ten modal vobec nemal zobrazit vytvorene credentials a sa zavrel takze credentials by sa zobrazili v notifikacii(ktore este nemame) bez timeoutu.

**Comment by kacurez** [comment]
aha to je dobre napad
