### ISSUE TITLE
Reload app icon after update

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#245]
Presunute z #123 

> tu je to komplikovanejsie, moze sa stat, ze tak ikonka este nebude spracovana a ked spravim "get" na app detail este dostanem staru (neham na rozmyslenie)

Skusal som tam dat setTimeout na "fetch app detail", no to riesenie sa mi moc nepaci, necham to este otvorene.

**Comment by ondrejhlavacek** [comment]
detail appky by se mohl neblokovaně načítat při každý akci s appkou, stejně tak seznamy?

**Comment by ujovlado** [comment]
Momentalne to fici tak, ze pri kazdom requeste na detail/edit apky sa robi request na detail (pre ten edit je to dobre, aby si vzdy editoval, pokial mozno, co najaktualnejsiu verziu). Takze je mozne, ze sa ti to pocas klikania proste reloadne - preto som tomu dal low prio.

Priklad:
- idem na edit apky
- zmenim ikonku
- vratim sa s5 (<- go back to app detail) na detail apky
- ikonku uz vidim

Co som si ale prave vsimol, ze to neupdatlo list, to fixnem!

**Comment by ujovlado** [comment]
Toto je zatial wontfix, pretoze by sa musel spravit reload komponenty, co prave v detaile robit nechcem. Ta zmena sa prejavi celkom rychlo a vo vacsine pripadov je po ulozeni apky ikonka uz nova.
