### ISSUE TITLE
Open app receive - handle also failure

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#26]
@kacurez pri auth akciach handlujem vzdy tri typy akcii: request, success a failure ... nespravil by si to aj pre open/apps?

**Comment by ujovlado** [comment]
related to #24, #16

**Comment by kacurez** [comment]
ok, v tomto pripade mi pride ze by sa to malo poriesit aj cez to nacitania dat na route
https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/common/PendingLayoutRoute.js#L39
takze action fetchData z open/apps vrati chybu a v tej route sa chyba zobrazi^^. 
Samotny container open/apps tu chybu vobec nemusi riesit

**Comment by ujovlado** [comment]
no ten container asi iba potrebuje vediet, ci sa to loaduje alebo nie ... alebo zavedieme nejaky globalny stav (v roote state) `isLoading`?

**Comment by ujovlado** [comment]
To je vlastne to, co sme vcera volali ... mozno by som to este nechal ulezat chvilku a poriesime to buduci tyzden?

**Comment by ujovlado** [comment]
T.j. mozno by tuto issue stacilo spravit tak, ze ked nastane chyba, tak nastavi `isLoading` na false (v ramci svojho kontextu `open.apps.isLoading`)

**Comment by ujovlado** [comment]
Ja som to v autorizacii zatial tiez neriesil dispatchujem error len v jednej casti:
https://github.com/keboola/developer-portal-ui/blob/a8e51a4/src/scripts/modules/auth/actions/login.js#L44

a ten network error este doriesime (asi aj podla toho ako sa syncneme s designom)

**Comment by kacurez** [comment]
imo sa to da poriesit uz teraz :)
ten globalny stav tam uz je: https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/common/PendingLayoutRoute.js#L36

`isLoading` sice v open/apps je ale vobec sa nepouziva a chystam sa ho vyhodit, som cakal ze sa na nieco hodi ale vobec som ho nevyuzil nakoniec.

ked nastane chyba pri nacitani dat tak nema zmysel rendrovat tu stranku rovnako ako ked sa loaduje tak je tam `Loading..` by som vyrendroval chybu v tej pending route.

**Comment by kacurez** [comment]
autorizacia do PendingRoute nepatri - tam sa to musi handlovat  "rucne".

**Comment by ujovlado** [comment]
jo, to bol len priklad, ze to neriesim :)

**Comment by ujovlado** [comment]
pockat, ale nechcl si ten lokalny state z pending route vyhodit?

**Comment by kacurez** [comment]
myslel som to tak ze ho napojim na redux a nie ze uplne vyhodim - teraz je to ako plain react state ale nicomu to nevadi.

**Comment by ujovlado** [comment]
ok, ak chces tak to sprav, no ja by som to este nechal ulezat, nie je to uplne trivialna vec :)

zaujima ma ako sa to bude chovat:

success:
0. som na resources
1. kliknem na apps (na miesto contentu sa zobrazi loading...)
2. ked to dobehne, loading sa zameni za appky
3. zmeni sa routa

... teraz asi nemusime riesit, ci sa zmeni routa v hned alebo az po success)

error:
0. som na resources
1. kliknem na apps (na miesto contentu sa zobrazi loading...)
2. nastane error, loading by sa mal vypnut
3. co sa stane? da ma na predoslu route a vyrenderuje mi spat stranku, kde som bol a niekde zobrazi error? alebo nemiesto loading zobrazis error?

**Comment by kacurez** [comment]
teraz by som zobrazil namiesto `Loading..` error + hlasku `Contact support or refresh page`  - to by bolo rovnake aj keby si to riesil kontajner sam.
V kbc-ui to mame tak ze sa error zobrazi ako notifikacia takze ostava vyrendrovana stara routa - to je hlavne vdaka tomu ze `Loading` sa zobrazuje ako tociacesa kolecko v layoute vedla breadcrumbs.

**Comment by ujovlado** [comment]
takze tu stranku vyrenderuje s errorom a aj sa normalne zmeni route ... to zni fajn

**Comment by ujovlado** [comment]
potom este mozeme predebatovat ako sa chovat pri network errore, ale to je ina issue :)
