### ISSUE TITLE
Unnecessarily required fields for saving the app

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal-ui#276]
Pole documentationUrl, longDescription, atd. nejsou povinný pro uložení aplikace, ale až při žádosti o publikaci (při odesílání se to kontroluje i v API). Co jsem se tak setkal už víckrát na Zendesku, tak to většinou při testování appky nikdo nemá a cpe tam stejně nějaký placeholdery.

**Comment by ujovlado** [comment]
@JakubMatejka su uz povinne len `name` a `type`. Chcel som tym zabranit aby sa nestalo, ze niekto po publikovani odstrani hodnoty z fieldov, ktore boli required pre publikovanie. To je ale ina issue. :)
