### ISSUE TITLE
Fetch application detail

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#28]
- route napr. `/apps/keboola.ex-twitter`
- csska netreba riesit

Neviem ci obsahuje detail appky viac informacii ako to co je v liste.

- Ak nie, tak asi budme moct pouzit data, co uz mame v state
- Ak ano, tak to bude treba nacitat znovu

resp. mozeme to nacitat znovu asi vzdy a vysledok mergnut do hlavneho listu? asi potom bude treba pridat do toho pola s aplikaciami (`open.apps.data`) aj keys

**Comment by kacurez** [comment]
pozeram ze detail apky obsahuje viac infa. Je asi jedno ako sa to ulozi - dolezity je selector a ten bude nieco getAppDetail takze by som to kludne ulozil zvlast.

**Comment by kacurez** [comment]
narazil som na problem - cesta musi byt ako ma api tj `apps/vendor/appid`
pretoze ak pridem rovno na `/apps/keboola.ex-twitter` tak neviem jej vendora a musim cakat kym sa nacita apps list, lenze fetchApps sa vola sucasne s fetchAppDetail takze ten detail nema ako pockat kym sa nacita zoznam apiek a z toho vysosat vendora potrebneho k api callu detailu apky.
jedine co ma napada je dodrzat cestu tak ako ma definovane api tj `apps/keboola/keboola.ex-twitter` alebo si cez api nacitat zoznam apiek ale ta stranka potom bude pomala(budu sa volat 2 api cally za sebou)

**Comment by ujovlado** [comment]
@kacurez vendora si mozes ziskat sparsovanim app id :)

**Comment by ujovlado** [comment]
ale pri starych apkach je to v prdeli ... `wr-google-drive` ... tak nic, daj tam vendora

**Comment by kacurez** [comment]
jj zatial to mam urobene ako `apps/vendorid/appid` - potom to ked tak neni problem zmenit.
