### ISSUE TITLE
[PendingLayoutRoute] move react state to redux state + actions + tests

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#30]
nahradit volania `this.setState` prislusnym redux `dispatch({requestFetchData, receiveFetchData, failFetchData})` v PendingLayouteRoute, napr tu:
https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/common/PendingLayoutRoute.js#L34
K tomu dopisat testy reduceru na dispatch fetchData actions.
Tie redux moduly by som dal do zlozky fetchData tj `src/scripts/modules/fetchData/{reducers.js,actions.js, reducers_spec.js}`.

**Comment by ujovlado** [comment]
Toto uz netreba :)
