### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#305]
Když kliknu na Account hodí mi to:
![image](https://user-images.githubusercontent.com/903531/30582774-36bae898-9d25-11e7-9623-f8bfbe6fada3.png)

**Comment by Halama** [comment]
Zbavím se toho smazáním storage appky v browseru.

**Comment by ujovlado** [comment]
@Halama myslis, ze sa mohlo stat, ze si sa uz mesiac neprihlasil?

```
refreshToken - is used for refreshing an auth token using the API call below, is valid for 30 days
```

Nemal si nahodou otvorenu console, ze by si mi povedal ake actions tomu predchadzali? :)

**Comment by ujovlado** [comment]
Asi tam pridam nejake logovanie ... alebo ta v takomto pripade automaticky odhlasim

**Comment by Halama** [comment]
Jo prihlasoval jsem se naposled hodne davno.

**Comment by Halama** [comment]
bude to tim.

**Comment by Halama** [comment]
pockej mesic a muzes si to vyzkouset :)

**Comment by ujovlado** [comment]
pridam do tokenu nejake random znaky a testnem to ... bude to teda odhlasovat - nic ine s tym nemozem urobit, ked je neplatny token ;)

**Comment by ujovlado** [comment]
Fixnem dnes.
