### ISSUE TITLE
Review Jack (part 1)

### ISSUE THREAD

**Issue by jancermak** [keboola/developer-portal-ui#316]
Desktop verze:

> - [x] home — odkaz do resources — http://take.ms/OMdfa

hotovo: #329  

> - [x] schovat tlacitka na pridani appky a developera — http://take.ms/TVTFK abych je videl jenom kdyz kliknu na sekci app respektive developer. Proc - konzistence u service accounts to narazime na to ze se nam to nevejde nahoru. Tedy navrhuju sjednoceni.

super, tiez som to tak chcel #330

———————

> - [x] apps — zvyraznena polozka menu, kde jsem — http://take.ms/78Ge8

opravene v #332

> - [x] apps - search — jde aby vyhledavani v aplikacich fungovalo bez potreby potvrzeni, napisu text a rovnou bez entru uz mi to ukazuje profiltrovane aplikace

poriesi sa v #367 

> - [x] apps — pridat ikonu lupy, a krizek na smazani inputu — http://take.ms/PnL5N 

hotovo v #375 

> - [x] apps — empty stav zadny vysledek vyhledavani

nieco som tam dal, ak sa ti tento styl bude pozdavat, mozeme to dat aj inde. #333

> - [x] apps — fixnuta hlavicka filtrovani — http://take.ms/YG0Ab

Skusim doladit v ramci #373

> - [x] apps — po kliknuti na appku  se otevre detail a neni zascrolovano nahoru na hlavicku detailu — viz video http://take.ms/eXQzo

To je bug, fixneme v #372

———————

> - [x] apps/detail — logo aplikace — vetsi a zarovnany na stred? je mozne? — http://take.ms/oMgSX

~Tym zarovnanim na stred som si nie moc isty, akonahle je v tom strednom boxe viac contentu, vyzera to divne (hlavne pri vendor info): https://user-images.githubusercontent.com/419849/31298146-0deadf1e-aae9-11e7-8e4f-2154dca2504f.png~ poriesi sa ako sa pise tu: https://github.com/keboola/developer-portal-ui/issues/316#issuecomment-341077879

> - [x] Velikost loga aplikace - ted je to 64x64, pozadoval bych ale minimalni velikost  128x128 at mame dostatecne kvalitni obrazek i pro retinu.http://take.ms/FbqUR

Zalozil som issue v devportal (https://github.com/keboola/developer-portal/issues/158), mozeme doriesit tam.

> - [x] apps/detail — texty v zakladni popisce aplikace — http://take.ms/NJQqh

poriesene v #336, na stred som to nezarovnaval (vid. comment pri ikonke)

> - [x] apps/detail — modre nadpisy v textu (H3) — http://take.ms/xvWyh — trochu to ozivi tu sadu textu

vybavene: de8ccd7502a5b198d215ad17dfcacbd55c16af82

**Comment by ujovlado** [comment]
@jancermak rozdelil som to tu na 3. casti (vid. issues)

**Comment by jancermak** [comment]
ok — mam rozkresleno co tam chybi za me

**Comment by jancermak** [comment]
@ujovlado — pridal jsem do invisionu prvni cast chybejicich veci ode me — https://invis.io/DGAIQD6Y7#/258984355_KDP_-_Changes_Upgrades_1
Je to ve stejnem projektu co jsi prihlasen a v seznamu screenu je to az na konci.

**Comment by ujovlado** [comment]
@jancermak tiez zmeny su super, zapracujem a potom dam vediet ;)

**Comment by jancermak** [comment]
@ujovlado — pridavam upravenou editaci detailu aplikace. Nahrano do invissionu. V seznamu to najdes az dole na konci.

Empty stav: https://invis.io/DGAIQD6Y7#/261471136_Account_-_Edit_App_Detail_Empty_V2_Copy
Vyplneny stav: https://invis.io/DGAIQD6Y7#/261471137_Account_-_Edit_App_Detail_Filled_V2

**Comment by ujovlado** [comment]
@jancermak parada, dalsie kolecko by som hodil koncom tohto, zaciatkom buduceho tyzdna :)

**Comment by jancermak** [comment]
@ujovlado  — a timto by to melo byt vse pro prvni kolo review

https://invis.io/DGAIQD6Y7#/261545010_KDP_-_Changes_Upgrades_2

**Comment by ujovlado** [comment]
@jancermak podobne ako som pisal v predch. casti, vacsina je poriesena a niektore maju uz separatne issues. ;) Tu to zavrem
