### ISSUE TITLE
URI k repository

### ISSUE THREAD

**Issue by padak** [keboola/developer-portal-ui#324]
Do URI dal týpek celou cestu

`https://hub.docker.com/r/bizztreat/keboola-ex-ewaycrm-writer/`

místo

`bizztreat/keboola-ex-ewaycrm-writer`

Opravil jsem to, ale bylo by super, kdyby si to UI při editaci komponenty pohlídalo. Jde o tohle:
![image](https://user-images.githubusercontent.com/1427901/31219204-de5b7ace-a9bc-11e7-9dd8-3877a6abc793.png)

**Comment by ujovlado** [comment]
Jo, to fixneme, nech tam nemoze dat URL, pripadne mozno premenovat. Skoda, ten placeholder si asi nevsimol.

**Comment by ujovlado** [comment]
Bude opravene v dalsom release.

![screenshot_2017-10-05_17-26-57](https://user-images.githubusercontent.com/419849/31235718-7d2a9862-a9f2-11e7-9db5-78966c37aadc.png)

**Comment by ujovlado** [comment]
Este som tam prihodil repository:
![screenshot_2017-10-05_19-23-39](https://user-images.githubusercontent.com/419849/31240999-bf8c4b0a-aa02-11e7-93d1-a2ba306bb1f8.png)
