### ISSUE TITLE
show kbc sync status for every app

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#327]
Napadlo ma zaviest pre kazdu stranku komponenty refresh ikonku ktora bude signalizovat sync stav developer portalu s kbc. Takze updatnem apku a chvilu to bude "svietit" ze je neaktualne a tym s istotou viem ze zmeny este niesu zavedene. 
Momentalne je mozne si to komplikovane zistit cez https://connection.keboola.com/v2/storage ale vacsina userov otom nevie. Tiez tu neaktualnost zmien si vela userov imho neuvedomuje..a potom mozu vznikat zmatky.

**Comment by kacurez** [comment]
Ale asi problem bude vobec zistit ze apka je/neni syncnuta kedze to niesu 1:1 js objekty

**Comment by ujovlado** [comment]
Myslim, ze by stacilo, ak spravne vykomunikujeme, ze sa to deje raz za par minut.

Tie nejasnosti asi vznikaju na zaciatku, ked to niekto chce debugovat v connection. A asi hlavne pri upravach, co chce vidiet (description, a pod.).

Neskor, ked sa uz upravuje len cislo verzie, to moze byt celkom priamociare a cele to updatnes skrz CI - a ak presli testy, nezaujima ta, kedy to bude syncnute, resp. kedy si to prvy user spusti.

**Comment by ujovlado** [comment]
Zavrem, doriesime to v ramci #360.
