### ISSUE TITLE
URI -> Image Name

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#339]
![image](https://user-images.githubusercontent.com/4319320/31320242-a274de1c-ac71-11e7-9661-b30675913b97.png)

- it is not uri but an image name (https://docs.docker.com/engine/reference/commandline/pull/#usage)
- message is wrong when field is empty
- put AWS ECR first ?

**Comment by ujovlado** [comment]
Nice! I will change it. It'll be fixed in next version ;)

**Comment by odinuv** [comment]
also, when saving app - URI is required but type is not - i.e. this is "valid"

![image](https://user-images.githubusercontent.com/4319320/31320596-6334abb4-ac77-11e7-898f-50313e052b85.png)

**Comment by ujovlado** [comment]
> also, when saving app - URI is required but type is not - i.e. this is "valid"

Yes, but we discussed (probably with @JakubMatejka ), that there are many situations when developer don't know what will be in the repository section (e.g. he don't know where to host image) and by setting repository section required, we deny him to edit app at all.

**Comment by ujovlado** [comment]
Tu sme to riesili #276

**Comment by odinuv** [comment]
ale URI ted povinny je, tak klidne at neni, ale pokud bude zadany, tak type musi byt taky

**Comment by ujovlado** [comment]
> message is wrong when field is empty

toto som posral nedopatrenim, fixnem to este pred tym zvyskom
