### ISSUE TITLE
Add links to docs

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#340]
app edit page:
- [x] https://developers.keboola.com/extend/common-interface/logging/#gelf-logger
- [x] https://developers.keboola.com/extend/common-interface/folders/#exchanging-data-via-s3
- [x] https://developers.keboola.com/extend/registration/configuration-schema/
- [x] https://developers.keboola.com/extend/registration/#ui-options
- [x] https://developers.keboola.com/extend/common-interface/actions/
- [x] https://developers.keboola.com/overview/encryption/
- [x] https://developers.keboola.com/extend/common-interface/folders/#default-bucket
- [x] as in https://github.com/keboola/developer-portal-ui/issues/340#issuecomment-335104259 bellow
- [x] Fees

**Comment by odinuv** [comment]
also add a few-words explanation to:
- Forwards token: No
- Forwards token details: No
- and fees in app edit

**Comment by odinuv** [comment]
also limits is not described properly - it should contains "reasonable usage" -- "Service limits / Reasonable usage | Description of service or usage limits. Define what is maximum expected usage of your component. This may vary depending on the memory/time limits, API usage limits and other factors." -> it does not have to be a hard limit

**Comment by ujovlado** [comment]
I added descriptions as mentioned above.

It will look like this:

![screenshot_2017-11-19_23-51-26](https://user-images.githubusercontent.com/419849/32996585-d5ff1228-cd84-11e7-8331-4bfe4e7cdba2.png)

**Comment by ujovlado** [comment]
Regarding https://github.com/keboola/developer-portal-ui/issues/340#issuecomment-335103544

> also add a few-words explanation to:
> 
> Forwards token: No
> Forwards token details: No

Forward token [ details] options are available only for us (admins). If we're planning to show them, descriptions will be added later.

> and fees in app edit

added
