### ISSUE TITLE
where is long description

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#342]
somehow let the user know that long description is down below, it's not clear from first sight

![image](https://user-images.githubusercontent.com/4319320/31320572-09aaa594-ac77-11e7-8a6b-0ef72c373c7e.png)

**Comment by ujovlado** [comment]
@odinuv napr?

![screenshot_2017-10-09_22-21-33](https://user-images.githubusercontent.com/419849/31356947-40474a2a-ad40-11e7-860b-dd7bfa9d3a62.png)
