### ISSUE TITLE
[idea] highlight almost required fields

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#343]
Repository is required for saving app. Otherwise everything else is optional - short description, license, configuration schema, long description (probably something else too?) are practically required for app approval - bring user attention to them?

**Comment by ujovlado** [comment]
Related to #276

**Comment by odinuv** [comment]
yup, agree - therefore 'highlight' (or emphasize) not 'make required'

**Comment by odinuv** [comment]
replaced by https://github.com/keboola/developer-portal-ui/issues/395
