### ISSUE TITLE
show mem and timeout

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#344]
- show readonly values of Processing timeout and Required memory to the user
- show instruction how to change it (= ask support)

**Comment by odinuv** [comment]
also perhaps skip showing Configuration format: json - it's deprecated already

**Comment by ujovlado** [comment]
> also perhaps skip showing Configuration format: json - it's deprecated already

While editing, there's no configuration format. So I removed it also from "view mode". I can think of situation when it'll be needed in admin part, but we can add it later. d00e212

**Comment by ujovlado** [comment]
Already in app detail:
![screenshot_2017-11-17_21-16-16](https://user-images.githubusercontent.com/419849/32967082-9458f5e0-cbdc-11e7-92e0-732a91b76d75.png)

So I'm going to add it to app editing.
