### ISSUE TITLE
hide weird UI options?

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#345]
- genericUI 
- genericShinyUI 
- excludeRun

**Comment by Halama** [comment]
přidal bych tam i `deprecated`. To by se tam nabízet nemělo protože už to přímo podporuje dev poratal a do ui options se mergne při syncu v kbc https://github.com/keboola/connection/blob/55673232c4f146f6be3d8d0afd979f850f66480a/library/Keboola/DeveloperPortalAppSync.php#L158

**Comment by ujovlado** [comment]
Ok, vyhodim vsetky 4 a spravim to tak, ze sa nebudu dat pridavat ale budu sa dat len odobrat.
