### ISSUE TITLE
New app - dash added to app id

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#349]
![image](https://user-images.githubusercontent.com/903531/31771849-e54502d4-b4dd-11e7-8a5f-11ccf157e3cf.png)

**Comment by Halama** [comment]
aha už jsem to pochopil, ono se to jěště změní po vybrání typu :) ale stejně je to divný

**Comment by odinuv** [comment]
jo taky me to zmatlo, nemelo by tam to id byt dokud neni typ vybrany

**Comment by Halama** [comment]
mě to právě zmátlo už na podruhý, tak jsem to issue přecijenom nakonec radši založil

**Comment by Halama** [comment]
co to tam vůbec nezobrazovat?

**Comment by ujovlado** [comment]
Vyriesil by som to ako pise Odin:

> jo taky me to zmatlo, nemelo by tam to id byt dokud neni typ vybrany

Ak by sme ho tam vobec nezobrazovali, tak sa ti nepodari zalozit 2x komponentu s rovnakym nazvom (co sa nam deje bezne, ked nieco deprekujeme - vtedy sa meni len jej IDcko.)
