### ISSUE TITLE
update docs links

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#354]
remove boiler-plate texts:
- how to make app
- how to test app
- faq

add relevant stuff
- specific parts of docs (instead of a generic link)
    - tutorial /extend/docker/quick-start/
    - common interface /extend/common-interface/ (data folders /extend/common-interface/folders/), (config file /extend/common-interface/config-file/)
    - registration /extend/registration/ (https://github.com/keboola/developers-docs/pull/50)
    - deployment /extend/registration/deployment/ (https://github.com/keboola/developers-docs/pull/50)
- docker tutorial /extend/docker/tutorial/ ?

**Comment by ujovlado** [comment]
Those dummy texts have been removed, I also added few "live" links to developers docs.

Remaining will be added once that PR is merged

**Comment by ujovlado** [comment]
Remaining links have been added.

![screenshot_2017-11-19_20-36-41](https://user-images.githubusercontent.com/419849/32994559-5d1afee6-cd69-11e7-8532-03d7ef36b884.png)
