### ISSUE TITLE
Can't find vendor id

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal-ui#359]
![image](https://user-images.githubusercontent.com/497675/32613251-aa73b8ce-c56a-11e7-8ff7-21a721044650.png)

**Comment by ondrejhlavacek** [comment]
A ideálně, kdybych na klik dostal rovnou filtr na appky danýho vendora

**Comment by ujovlado** [comment]
> A ideálně, kdybych na klik dostal rovnou filtr na appky danýho vendora

toto som presunul do #389, dobry napad :+1:

**Comment by ujovlado** [comment]
Kedze sa tu jedna o admin view, pridam ID vendora ko novy stlpec a dotunime to ak sa nam nebude zdat.
