### ISSUE TITLE
[idea] Show # of returned results from apps search

### ISSUE THREAD

**Issue by pivnicek** [keboola/developer-portal-ui#361]
![image](https://user-images.githubusercontent.com/569139/32835309-e58b1bb0-ca05-11e7-82f7-fdf8d1c0f7aa.png)

Could be cool to show `Found 32 apps matching the search criteria` or something

**Comment by ujovlado** [comment]
Sorry, but I see no value for user in that information. For me, it's a "wontfix". Anyway, you can discuss this with @jancermak :)
