### ISSUE TITLE
Vendors filter

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#380]
What is purpose of this select with one value? :)

![image](https://user-images.githubusercontent.com/903531/33314089-da56ff62-d42c-11e7-8090-cb063afb4e97.png)

**Comment by ujovlado** [comment]
To vyhodim, mala to byt moznost odfiltrovat si len vendorov, ktory cakaju na schvalenie. Ale chodi to do Slacku, tak to tam netreba. :) Mozeme to vratit, az to bude mozne na API.
