### ISSUE TITLE
superadmin developers listing broken

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#382]
ked vojdem na nasledujuci link tak sa to rozbije - tj nic sa nezobrazi
https://apps.keboola.com/admin/developers

![image](https://user-images.githubusercontent.com/1412120/33795883-002b9c00-dcea-11e7-87ad-bf8c7abcee54.png)
z chyby to odkazuje sem:
 https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/admin/reducers/developers.js#L86
https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/admin/containers/Developers.js#L39

co mi pride divne je ze sa to vobec neukazalo v #ui-errors ale v sentry som to nasiel:
https://sentry.io/keboola/developer-portal-ui/issues/415812433/

**Comment by ujovlado** [comment]
Idem to kuknut, uz som pri PC :)

**Comment by ujovlado** [comment]
Probably API bug: https://github.com/keboola/developer-portal/issues/170

**Comment by ujovlado** [comment]
Fixed in keboola/developer-portal#170

**Comment by ujovlado** [comment]
https://sentry.io/keboola/developer-portal-ui/issues/415812515/

**Comment by ujovlado** [comment]
https://sentry.io/keboola/developer-portal-ui/issues/415812392/

**Comment by ujovlado** [comment]
https://sentry.io/keboola/developer-portal-ui/issues/415812431/

**Comment by ujovlado** [comment]
https://sentry.io/keboola/developer-portal-ui/issues/415812433/

**Comment by ujovlado** [comment]
https://sentry.io/keboola/developer-portal-ui/issues/415812715/
