### ISSUE TITLE
App Detail Page

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal-ui#387]
The app detail is linked eg from weekly statuses. This is quite ugly and not saying much. Few tweakes will make it much better.

![image](https://user-images.githubusercontent.com/497675/34720460-17e550b2-f53f-11e7-94a1-3127d3133e95.png)

**Comment by ujovlado** [comment]
It'll be done as part of #335 and #376. After that we can discuss if it's sufficient or not.
