### ISSUE TITLE
Configuration Description input field with preview

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal-ui#388]
Dává se tam markdown, tak by se tam mohlo hodit preview jako je u dolního popisku

![image](https://user-images.githubusercontent.com/497675/34831405-27a91002-f6e7-11e7-9d19-d1aab56cd743.png)

![image](https://user-images.githubusercontent.com/497675/34831408-2984da0a-f6e7-11e7-8e37-7f3879fc4818.png)

**Comment by ujovlado** [comment]
Skusil by som to spichnut s tym ked sa bude revidovat app detail podla navrhov

**Comment by ujovlado** [comment]
Tu som si nie moc isty, ci to dat rovno do toho formulara - mam pocit, ze ho to potom rozbija.

Kludne by som tam dal preview button, ktory by to mohol zobrazit v modale - nepaci sa mi ale, ze to potom nie je konzistentne s tym, co je dole. :thinking:

**Comment by ujovlado** [comment]
Ale prave som si spomenul, ako to ma Zendesk, spravim to zatial podobne.

**Comment by ujovlado** [comment]
![peek 2018-02-17 22-38](https://user-images.githubusercontent.com/419849/36345856-6e7d4fde-1433-11e8-9dcc-ea3ccbc732ce.gif)

**Comment by ujovlado** [comment]
Related to #395
