### ISSUE TITLE
Create new components with genericDockerUI

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#396]
Components of type extractor, application and writer should have the `genericDockerUI` flag turned on by default. Without it they cannot be configured and it is supper annoying.
Alternative: set it to default for all components, and someone creating a processor can remove it later.

This is probably the most important step in https://github.com/keboola/developer-portal-ui/issues/394

**Comment by ujovlado** [comment]
I think we can add it conditionally - only for ex, wr and app. I'll do it.
