### ISSUE TITLE
New vendor property projectUrl

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal-ui#398]
Nová property vendora, měla by být nastavovatelná nejspíš jen z administrátorské sekce (viz. https://github.com/keboola/developer-portal/issues/159)

**Comment by ujovlado** [comment]
@JakubMatejka pozeram ale, ze je to dostupne v obidvoch castiach:

- https://kebooladeveloperportal.docs.apiary.io/#reference/0/vendor/create-a-vendor
- https://kebooladeveloperportal.docs.apiary.io/#reference/0/admin-vendors/create-a-vendor

Chceme to teda povolit userovi zadat aj pri zakladani vendora?

Chapal som to tak, ze tu property nastavujeme my, a tak v standardom vytvarani vendora nebude dostupna.

Spravim to zatial len do admin casti.

cc: @odinuv @ondrejhlavacek

**Comment by ujovlado** [comment]
Tak nakoniec to bude pridane vsade - je tam na to univerzalny form. V ramci dalsieho refaktoringu by som ten form rozbil na viac, a potom to necham len v admin casti.
