### ISSUE TITLE
Reautorizacia

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#4]
- aplikacia by sa mala sama na pozadi postarat o to aby sa refreshli potrebne tokeny
- malo by sa to diat z jedneho miesta, automaticky, povedzme 10 min pred vyprsanim?
- alebo az pri nejakom api calle, ked zistime, ze je token neplatny?

**Comment by kacurez** [comment]
v login response vidim `token`, `accesToken`, `refreshToken` a `expiresIn: 3600`. Automaticky refresh po nejakej dobe by som nerobil a radsej by som to refreshoval az pri nejakom api calle, ak nato user hodinu neklikne tak sa mu to "odhlasi".

**Comment by ujovlado** [comment]
Myslim, ze nam ide prave o to aby ho to neodhlasilo (preto sa tam dorabal refresh token) -> t.j. pri dalsom API calle (kludne po zobudeni notebooku po 2 hodinach) by to asi zistilo, ze request nebol so spravnym tokenom. Potom by to muselo ziskat novy access token a dany request zopakovat, aby to bolo pre usera transparentne.

Co asi budeme musiet spravit tak ci tak, lebo ak by z nejakeho dovodu nepresiel ten "refresh", stejne by to muselo spravit ten refresh pri api calle.

Takze riesenim asi bude nejake  "vrstva" cez ktoru pojdu vsetky requesty, nech to je na jednom mieste.

**Comment by kacurez** [comment]
s tou "vrstvou" suhlasim, to je jasne.
Akurat asi nie dobre rozumiem konceptu refreshu token, mam zato ze refresh token ma tiez nejaku platnost(asi tiez hodinu) tj po tych 2 hodinach uz request vyfailuje tym ze sa nepodari refreshnut acces token. ci?

**Comment by ujovlado** [comment]
Keby obdiva mali platnost hodinu, nedavalo by to zmysel mat 2.

Chapem to takto:
- `token`: hodinu platny, ked s nim robim po hodine req. dostanem 4xx response
- `accessToken`: nejake vec kvoli MFA :)
- `refreshToken`: s tymto mozem poziadat kedykolvek(?) o novy `token` http://docs.kebooladeveloperportal.apiary.io/#reference/0/auth/refresh-token

**Comment by ujovlado** [comment]
Jop, tu to je: http://docs.kebooladeveloperportal.apiary.io/#reference/0/auth/login ... `accessToken` plati hodinu, `refreshToken` 30 dni

**Comment by ujovlado** [comment]
^ Mam to uz premyslene, assignem si to ... bude to riesit ta "fetch proxy", ako sme sa bavili

**Comment by ujovlado** [comment]
Takto to fici, skusal som to pri nacitani  user profile (tam vidno prvy req., ze bol 401 a potom to reautorizovalo)

![screenshot_2017-05-31_19-00-00](https://cloud.githubusercontent.com/assets/419849/26667492/c74dd37e-46a5-11e7-8e63-01bc2480532d.png)
