### ISSUE TITLE
Display MFA key along with the QR code 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal-ui#464]
> In my case, Blackberry phone could not scan QR code by Google authenticaton app which is not a native application for BB10

https://keboola.zendesk.com/agent/tickets/8143
https://keboola.slack.com/archives/C02CGRFGU/p1522145120000089

**Comment by ujovlado** [comment]
Len doplnim, ze "open image in new tab" v nasom pripade clovek spravit nemoze, je to canvas.
