### ISSUE TITLE
Remove encryption

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#467]
all components now use encryption, flag is useless

**Comment by ujovlado** [comment]
poriesim poobede/vecer

**Comment by odinuv** [comment]
az po https://github.com/keboola/kbc-ui/issues/1621 projistotu :)

**Comment by ujovlado** [comment]
no ja by som ho tam nastavil na `true` pre vsetky nove komponenty, starych by som sa nechytal. a az bude jedno, ci to je true/false, vyhodil by som to odtial uplne. ;)

**Comment by odinuv** [comment]
nastavovat to nejak nema smysl a uz vubec ne jen pro neco, kdyz uz tak nastavit na true pro vsechny, ale pokud se vyhodi ta podminka z UI, tak bude uplne jedno jakou to ma hodnotu

**Comment by ujovlado** [comment]
aha, ok, tak pockam na to vyhodenie, aby to bolo sumak ;)
