### ISSUE TITLE
"Configuration description" preview is not working

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/developer-portal-ui#472]
![image](https://user-images.githubusercontent.com/642928/39184806-29f57f56-47c5-11e8-9a80-91a9fc76c6b4.png)
![image](https://user-images.githubusercontent.com/642928/39184823-35356aac-47c5-11e8-9006-b03fb854d1a6.png)

(moved from https://github.com/keboola/developer-portal/issues/194)

**Comment by ujovlado** [comment]
@tomasfejfar could you provide configuration description for which preview is not working for you?

**Comment by tomasfejfar** [comment]
Sent via slack

**Comment by ujovlado** [comment]
I'm confirming that it's not working in admin section at all.

**Comment by ujovlado** [comment]
deployed
