### ISSUE TITLE
Align "you" label

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#503]
From Jack's review

http://take.ms/xYzd7

**Comment by ujovlado** [comment]
Deje sa to v zozname developerov, inde myslim nie. 

Asi staci ak sa poriesi tento specificky pripad, nemusi to byt asi nejako ultra univerzalne.

**Comment by ujovlado** [comment]
Je to teda na 2 miestach (admin a home) , UsersTable.

**Comment by natocTo** [comment]
Text mi zarovnaný přijde. Ale asi teda jde o to, aby i s tím paddingem okolo to bylo na stejné úrovni. Teda text (you) ve výsledky výše.
