### ISSUE TITLE
call it "developer portal somewhere

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#507]
it just says "developer" everywhere :)

**Comment by ujovlado** [comment]
what about shorthand “devportal”? (it’s almost same length so it won’t affect UI much)

**Comment by jancermak** [comment]
@odinuv
1)topic is this?
![image](https://user-images.githubusercontent.com/1826442/41660162-941d0144-749b-11e8-8e3a-958fc305ad53.png)

@ujovlado 
2) you mean this way
![image](https://user-images.githubusercontent.com/1826442/41660395-352905ce-749c-11e8-85d4-fe3639d28ecb.png)

Offtopic?
Now I was in situation, that I didnt remeber URL :-) My solution was google it — 
![image](https://user-images.githubusercontent.com/1826442/41660233-c7f48be0-749b-11e8-9330-92599b87b04c.png)

Keboola Developer Portal = Components ?

**Comment by odinuv** [comment]
napr. z https://developers.keboola.com/extend/component/tutorial/#before-you-start

> To be able to create new components, you also need to have an account in the [Keboola Developer Portal](https://components.keboola.com), which manages the list of components available in KBC

kdyz se prokliknes na ten link, tak tam nikde neni receny, ze jsi se dostal na Developer Portal a lidi jsou z toho zmateni jestli se nemaji jako prokliknout jeste nekam jinam. Prejmenovat to na "Components" by imho byl jeste vetsi zmatek.

**Comment by ujovlado** [comment]
Ano, je to tak ako pises, bavime sa o tom napise "Developer". Po spravnosti by tam malo byt asi "Developer Portal", no napadlo mi ci to neskratime. Slovo "dev" je celkom zauzivane. Tak to moze byt "DevPortal" asi. Alebo nie? :)

**Comment by ujovlado** [comment]
Meno "sluzby" je Developer Portal resp. Keboola Developer Portal. To ze sme to zavesili na inu domenu asi ani tak nevadi (ak ked mohlo by to byt na devportal.keboola.com, no to by uz bol 3 presun :rofl: ).

Prave som si vsimol, ze si to v tom screene upravil - to sa mi paci. https://user-images.githubusercontent.com/1826442/41660395-352905ce-749c-11e8-85d4-fe3639d28ecb.png

Tak ak sa na tom zhodneme, upravil by som to.

**Comment by jancermak** [comment]
![image](https://user-images.githubusercontent.com/1826442/41661989-505e6d94-74a0-11e8-8cef-651b17e41285.png)
![image](https://user-images.githubusercontent.com/1826442/41662012-60cbb3a8-74a0-11e8-9efc-bf6296ef7f97.png)

**Comment by jancermak** [comment]
@ujovlado — koukal jsem ze to tam mas PNG. To co se vybere chces poslat jako PNG nebo zkrivkovat i pismo a poslat jako SVG?

Puvodni moje myslenka byla ze to bude ikona kebooly (SVG) + k tomu pridas ten nazev jako text (je to tim fontem Gotham)

**Comment by ujovlado** [comment]
Varianta 1 je imho super, nie je to zbytocne dlhe a vieme co to zmanena.

Aha, ja som to robil vtedy narcyhlo, tak som to svacol ako png. Staci mi asi svg chobotnice a zvysok dam normalne Gotham ako pises.

**Comment by jancermak** [comment]
[keboola.svg.zip](https://github.com/keboola/developer-portal-ui/files/2119551/keboola.svg.zip)

**Comment by jancermak** [comment]
me se libi: Developer Portal — nevyhoda je ta delka. Coz by v te responzivite mohlo v necem vadit.
Beru ze vy jste vice cilova skupina —> takze je pro me cajk i  DevPortal.

**Comment by odinuv** [comment]
ja su mirne naklonenej " Developer Portal", protoze nemam rad zkratky, ale je mi to celkem jedno :)
