### ISSUE TITLE
Component id is really confusing on component creation page

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#510]
In home module us this (which is great):

![screenshot_2018-06-20_16-39-21](https://user-images.githubusercontent.com/419849/41665646-b7ae8350-74a8-11e8-82c9-6f8af3788ea3.png)

But in admin part:

![screenshot_2018-06-20_16-38-50](https://user-images.githubusercontent.com/419849/41665676-cf648828-74a8-11e8-9d82-f61e871f2bdc.png)

We should use the same input as above (in home module), because component ID will be prefixed. And change that prefix "on vendor change".

**Comment by Halama** [comment]
I think we don't need add component button in admin.

**Comment by ujovlado** [comment]
Maybe not, but what will be proper solution to something like ZD ticket when someone is asking you to create component for him? Joining his vendor and creating component? If so, then component creation for admin is not really needed. :)

**Comment by Halama** [comment]
He can create a component by himself so why would we create it for him? :)

**Comment by ujovlado** [comment]
Deprecated by #511
