### ISSUE TITLE
Cannot save new repository tag

### ISSUE THREAD

**Issue by ErikZigo** [keboola/developer-portal-ui#521]
Editing repository tag of components fails with error
![image](https://user-images.githubusercontent.com/1726727/43848016-4f563978-9b32-11e8-875c-135b5ab90525.png)

![image](https://user-images.githubusercontent.com/1726727/43847942-24b3062e-9b32-11e8-88ce-c095e36abf2a.png)

Example component: https://components.keboola.com/~/components/keboola-test.app-vlado-test/edit

It is only in user mode. Admin mode works fine for component edit.

**Comment by ujovlado** [comment]
je to kvoli `digest`, ako som pisal ... fixnem to dnes
