### ISSUE TITLE
Validate component memory setting

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#528]
> Most of these options take a positive integer, followed by a suffix of b, k, m, g, to indicate bytes, kilobytes, megabytes, or gigabytes.

Sou we should only allow those 4 "suffixes".

Right now it is very easy to make a typo.

**Comment by ujovlado** [comment]
@natocTo myslim, ze by si si este mohol skusit napr. toto

**Comment by natocTo** [comment]
Kde to najdu. Nějaký memory limit vidím u editace komponenty. Ale tam to mám disabled (toto + timeout). Tak nevím zda mám otevřenou jen špatnou komponentu nebo jsem úplně špatně.

**Comment by odinuv** [comment]
musis se prepnout na admina

**Comment by ujovlado** [comment]
Jo, nestihol som ta este adminom spravit. Hned to bude. Skusaj to ale na nejakej testovacej komponente ;)

**Comment by ujovlado** [comment]
Mas tam admina, je nutne sa odhlasit/prihlasit.

**Comment by natocTo** [comment]
Jo, už dobrý. Díky.
