### ISSUE TITLE
set defaultBucket:true when creating extractor component

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal-ui#542]
ked uzivatel vytvara komponentu a je typu extractor tak by sa mu pritom mal zapnut aj defaultBucket so `stage=in`. Default bucket maju takmer vsetky extraktory a teda je lepsie prehliadnut ze kompoenta ma defaultBucket nez ze ho nema. V pripade ze ho nema konci prvy importny job s hlaskou typu `"usersxyz" is not valid table identifier`

**Comment by ujovlado** [comment]
@odinuv s tebou me myslim zapinali pre vsetky nove komponenty "generic docker ui" ... co si myslis o tomto?

**Comment by odinuv** [comment]
jo, urcite jsem pro

**Comment by ujovlado** [comment]
ok, dik, poriesime to teda

**Comment by ujovlado** [comment]
@natocTo nechcelo by sa ti checknut toto? taka mensia vec.

- riesi sa to len pri vytvarani novej komponenty
- je tam metoda `setDefaultUiOptions` (mal by sa skor volat `setDefaultValuesOnCreation` alebo tak)
- ak je typ komponenty `extractor`, nech to nastavi `default bucket` na `true` a `default bucket stage` na `in`
- zaroven by sa uz na to oplatilo pridat testy
