### ISSUE TITLE
Remove unused test configuration?

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#550]
![image](https://user-images.githubusercontent.com/903531/48067086-a22ae480-e1cf-11e8-8b7e-48ef06871100.png)

**Comment by ujovlado** [comment]
Hm, fakt sa to nepouziva? Mne sa zda, ze som to niekde videl.

**Comment by Halama** [comment]
sorry, ještě jsem zapomněl kontext https://keboola.slack.com/archives/C1G9B2XMW/p1541509401004800
