### ISSUE TITLE
changes page broken

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#556]
![image](https://user-images.githubusercontent.com/4319320/49666581-cee54c80-fa58-11e8-8d1a-5b015847c5ac.png)

- it doesn't show the component for which the changes are displayed
- changed by is wrong
- changed on in wrong

![image](https://user-images.githubusercontent.com/4319320/49666552-becd6d00-fa58-11e8-95ff-6ec50128244b.png)

can be seen at https://components.keboola.com/admin/components/keboola.ex-db-mssql/changes

**Comment by ujovlado** [comment]
> it doesn't show the component for which the changes are displayed

poriesime

> changed by is wrong
> changed on in wrong

to bude na backend:

![screenshot_2018-12-07_19-52-32](https://user-images.githubusercontent.com/419849/49666883-aad63b00-fa59-11e8-8c30-120f474903f4.png)

**Comment by ujovlado** [comment]
Or if you know which values we should choose instead, I'll update it.
