### ISSUE TITLE
Invalid change date

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal-ui#560]
last 28 days a 2017?

![image](https://user-images.githubusercontent.com/497675/49898954-a4c9cb00-fe5a-11e8-8e61-d3ec6a5cac63.png)

v diffu navíc vidím správný datum

![image](https://user-images.githubusercontent.com/497675/49898967-b317e700-fe5a-11e8-8ff0-c359119d06cb.png)

**Comment by ujovlado** [comment]
Uz to reportoval  Odin v #556

Riesime to dalej v https://github.com/keboola/developer-portal/issues/271
