### ISSUE TITLE
Admin edit is broken

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal-ui#561]
- child "body" fails because ["isDeprecated" is not allowed]

https://keboola.slack.com/archives/C1G9B2XMW/p1544785859030400

btw ten checkbox jsem zrovna nedavno vyuzil pri deprekovani opustene appky

**Comment by ujovlado** [comment]
Fixnem to na UI,  no kym sa nefixne api  nepojdu deprekovat komponenty pre adminov.
