### ISSUE TITLE
List of developers

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#64]
- http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/list-users
- treba odtial odfiltrovat service accounty, kym nevieme, co s nimi (alebo sa mozu filtrovat cez dropdown a pridame dalsi stlpec "type") ... service account zacina prefixom vendora v emaili, takze napr. `keboola+`

Kukal som ale, ze to API moc toho nevracia, len email, desc a name, takze zatial bude ta tabulka celkom sucha :)

Tu je navrh od Jacka:
![screenshot_2017-06-13_10-38-04](https://user-images.githubusercontent.com/419849/27073522-6624ffd6-5024-11e7-8386-0529f0baa5a6.png)

**Comment by ujovlado** [comment]
O ten status som poziadal tu: https://github.com/keboola/developer-portal/issues/111 ... mozeme to pridat dodatocne.

**Comment by kacurez** [comment]
mi neide do hlavy co sa zobrazi na tej stranke developers, pretoze sa tam preklikam cez user ktory ma viac vendorov v nasledovnych krokoch:
1. prihlasim sa
2. do state sa ulozi email a token tj to co vrati login api call
3. redirectne ma to na admin/index
4. kliknem na developers ktory nacita zoznam `list-users: Lists all users of the vendor including service accounts` -> lenze ten berie parameter `vendor` a to v ten moment nemam(neni to ulozene v state ani v path)

napada ma: 
4. kliknem na developers => zavola sa api call `get-user-profile` ktory okrem ineho vrati pole `vendors`: ["gooddata", "bata", "rohlik"]
5. vyberie prvy prvok z pola(gooddata) a zavolam nadnim `list-users` a zobrazim

nejak podobne to imho naznacuje aj jackov navrh:
![image](https://user-images.githubusercontent.com/1412120/27084445-8894d01e-507e-11e7-9259-c68e8bbaa0f3.png)

mne osobne tam ta stranka vobec nepasuje - mozno ak by sa volala Vendors&Developers by to bolo lepsie.

**Comment by ujovlado** [comment]
aha, chapem .. no mal by si mat vybrateho vendora hned po prihlaseni (ak v nejakom si) ... prichystam ti to

**Comment by ujovlado** [comment]
zoznam vendorov uz mozes tahat cez `getProfile` selector

**Comment by ujovlado** [comment]
toho vendora si tam daj kludne zatial "keboola", uz mam takmer ready https://github.com/keboola/developer-portal-ui/issues/10, vysledkom toho bude, ze bude niekde v state a bude sa dat lahko selectnut

**Comment by kacurez** [comment]
ak je uzivatel vo viac vendoroch tak neni mechanizmus ako jedneho vybrat, jedine zobrat furt prveho z pola.

**Comment by ujovlado** [comment]
ano, kludne zober prveho z pola ... potom mozeme spravit syncnutie vybrateho do local storage alebo tak a budeme ti davat toho, co si mal posledne :)
