### ISSUE TITLE
Remove developer

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#65]
- z listu by sa mal dat odobrat developer z vendora (stlacenim Remove)
- http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/remove-user-from-a-vendor
- bolo by fajn to spravit cez "confirm modal"
- ked zmazem seba, malo by ma to redirectnut na "homepage admina", ked niekoho ineho, mozem ostat na tej istej stranke

**Comment by kacurez** [comment]
poriesene to v tychto PR:
https://github.com/keboola/developer-portal-ui/pull/74
https://github.com/keboola/developer-portal-ui/pull/78
https://github.com/keboola/developer-portal-ui/pull/68

ak sa odoberiem zo vsetkych vendorov tak sa mi zobrazi stranka `You're not a member of any vendor. + Create new vendor...` inac ostane na stranke s vybratym prvym moznym vendorom.
