### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#75]
- https://github.com/prettier/prettier
- https://github.com/okonet/lint-staged and https://github.com/typicode/husky
- prettier by sa pustal ako pre-commit hook, vzdy len na subory, ktore su staged
- prvy raz by sme to pustili manualne na celu codebase

**Comment by ujovlado** [comment]
@kacurez co myslis?

**Comment by kacurez** [comment]
ok, za pokus to stoji :)

**Comment by ujovlado** [comment]
ofiko navod z CRA:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically
