### ISSUE TITLE
Removed myself from vendor (last user) and vendor remains in profile

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#76]
Zmazal som sa z vendora, no v `auth.profile.currentVendor` mam stale povodnu hodnotu.

Myslim, ze reducer, ktory riesi current vendor, by mohol reagovat aj na `VENDORS_REMOVE_SUCCESS`?

Co je trosku naprd je, ze v tokene budu neaktualne data a nemozeme sa na ne spoliehat - takze asi nakoniec skoncime pri tom "get profile" :)

**Comment by kacurez** [comment]
nato som tiez narazil - napadlo ma urobit force refresh tokenu po zmazani seba a zaroven prenastavit currentVendor podla toho ci som sa zneho zmazal alebo nie.
https://github.com/keboola/developer-portal-ui/blob/master/src/scripts/modules/auth/reducers/profile.js#L41

**Comment by ujovlado** [comment]
skor by som sa priklonil k tomu "get profile" ... nemyslim si, ze odobranie sa z vendora je akcia, ktora ti ma refreshnut token :)

ale zase ten refresh tokenu sa ti tak ci tak udeje automaticky, tak mozno hej ...

**Comment by ujovlado** [comment]
sere ma, ze by sme refreshli token, ktory je validny ... preto rozmyslam nad "get profile"

**Comment by kacurez** [comment]
no praveze validny neni nie a mal by sa forcnut jeho refresh? pretoze ak sa odoberies z vendora tak si potom nemozes vylistovat jeho developerov - co v tomto pripade funguje.

**Comment by kacurez** [comment]
na druhu stranu malokedy sa odoberies z vendora a kvoli tomu furt pri kazdom nacitani developers volat getProfile mi pride zbytocne

**Comment by ujovlado** [comment]
> no praveze validny neni a mal by sa forcnut jeho refresh? pretoze ak sa odoberies z vendora tak si potom nemozes vylistovat jeho developerov - co v tomto pripade funguje.

hm, a ten api call, hned potom ako som sa odobral z vendora prejde?

**Comment by ujovlado** [comment]
> na druhu stranu malokedy sa odoberies z vendora a kvoli tomu furt pri kazdom nacitani developers volat getProfile mi pride zbytocne

jo, suhlasim ... to nacitanie z "get profile" tam mozeme pridat ak bude treba

btw, to by sa nevolalo stale ale len vtedy ked je treba (v podstate len pri akciach, co ti to mozu zmenit ... login, token refresh, zmena vendorov a pod.)

**Comment by kacurez** [comment]
> hm, a ten api call na list developerov, hned potom ako som sa odobral z vendora prejde?

 mne to preslo aj na nonadmin accounte.

> jo, suhlasim ... to nacitanie z "get profile" tam mozeme pridat ak bude treba

no ale getProfile sa na backendu tiez berie z tokenu, ktory v tom case stale obsahuje zmazaneho vendora:
https://github.com/keboola/developer-portal/blob/b7ca624/lib/Identity.js#L18
takze sa musi urobit refresh :)

pripravil som nato PR #78

**Comment by ujovlado** [comment]
ha, to mas pravdu! takze by to nepomohlo

**Comment by ujovlado** [comment]
super
