### ISSUE TITLE
Akcie v zozname aplikacii vendora

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal-ui#86]
Jedna sa o:
- request  approval: http://docs.kebooladeveloperportal.apiary.io/#reference/0/apps/request-approval
- request deletion: http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/delete-app

Obidva by som spravil cez "confirm modal":
![screenshot_2017-06-27_13-57-08](https://user-images.githubusercontent.com/419849/27586420-8bace634-5b40-11e7-8ec0-009f5d35a314.png)

A malo by to imho byt "make app public/nonpublic" alebo potom "publish/unpublish app"

**Comment by Halama** [comment]
nezni unpublic divne? :)

**Comment by ujovlado** [comment]
@Halama jo, to neexistuje asi, pisal som tam comment, ze tam dame nieco ine :)

**Comment by pivnicek** [comment]
Make this app private?
